# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.

struct FollowingApi <: OpenAPI.APIClientImpl
    client::OpenAPI.Clients.Client
end

"""
The default API base path for APIs in `FollowingApi`.
This can be used to construct the `OpenAPI.Clients.Client` instance.
"""
basepath(::Type{ FollowingApi }) = "https://misskey.qwjyh.net/api"

const _returntypes_following_create_FollowingApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => UserLite,
    Regex("^" * replace("400", "x"=>".") * "\$") => Error,
    Regex("^" * replace("401", "x"=>".") * "\$") => Error,
    Regex("^" * replace("403", "x"=>".") * "\$") => Error,
    Regex("^" * replace("418", "x"=>".") * "\$") => Error,
    Regex("^" * replace("429", "x"=>".") * "\$") => Error,
    Regex("^" * replace("500", "x"=>".") * "\$") => Error,
)

function _oacinternal_following_create(_api::FollowingApi, following_create_request::FollowingCreateRequest; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "POST", _returntypes_following_create_FollowingApi, "/following/create", ["bearerAuth", ], following_create_request)
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? ["application/json", ] : [_mediaType])
    return _ctx
end

@doc raw"""following/create

No description provided.  **Credential required**: *Yes* / **Permission**: *write:following*

Params:
- following_create_request::FollowingCreateRequest (required)

Return: UserLite, OpenAPI.Clients.ApiResponse
"""
function following_create(_api::FollowingApi, following_create_request::FollowingCreateRequest; _mediaType=nothing)
    _ctx = _oacinternal_following_create(_api, following_create_request; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function following_create(_api::FollowingApi, response_stream::Channel, following_create_request::FollowingCreateRequest; _mediaType=nothing)
    _ctx = _oacinternal_following_create(_api, following_create_request; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_following_delete_FollowingApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => UserLite,
    Regex("^" * replace("400", "x"=>".") * "\$") => Error,
    Regex("^" * replace("401", "x"=>".") * "\$") => Error,
    Regex("^" * replace("403", "x"=>".") * "\$") => Error,
    Regex("^" * replace("418", "x"=>".") * "\$") => Error,
    Regex("^" * replace("429", "x"=>".") * "\$") => Error,
    Regex("^" * replace("500", "x"=>".") * "\$") => Error,
)

function _oacinternal_following_delete(_api::FollowingApi, admin_accounts_delete_request::AdminAccountsDeleteRequest; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "POST", _returntypes_following_delete_FollowingApi, "/following/delete", ["bearerAuth", ], admin_accounts_delete_request)
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? ["application/json", ] : [_mediaType])
    return _ctx
end

@doc raw"""following/delete

No description provided.  **Credential required**: *Yes* / **Permission**: *write:following*

Params:
- admin_accounts_delete_request::AdminAccountsDeleteRequest (required)

Return: UserLite, OpenAPI.Clients.ApiResponse
"""
function following_delete(_api::FollowingApi, admin_accounts_delete_request::AdminAccountsDeleteRequest; _mediaType=nothing)
    _ctx = _oacinternal_following_delete(_api, admin_accounts_delete_request; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function following_delete(_api::FollowingApi, response_stream::Channel, admin_accounts_delete_request::AdminAccountsDeleteRequest; _mediaType=nothing)
    _ctx = _oacinternal_following_delete(_api, admin_accounts_delete_request; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_following_invalidate_FollowingApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => UserLite,
    Regex("^" * replace("400", "x"=>".") * "\$") => Error,
    Regex("^" * replace("401", "x"=>".") * "\$") => Error,
    Regex("^" * replace("403", "x"=>".") * "\$") => Error,
    Regex("^" * replace("418", "x"=>".") * "\$") => Error,
    Regex("^" * replace("429", "x"=>".") * "\$") => Error,
    Regex("^" * replace("500", "x"=>".") * "\$") => Error,
)

function _oacinternal_following_invalidate(_api::FollowingApi, admin_accounts_delete_request::AdminAccountsDeleteRequest; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "POST", _returntypes_following_invalidate_FollowingApi, "/following/invalidate", ["bearerAuth", ], admin_accounts_delete_request)
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? ["application/json", ] : [_mediaType])
    return _ctx
end

@doc raw"""following/invalidate

No description provided.  **Credential required**: *Yes* / **Permission**: *write:following*

Params:
- admin_accounts_delete_request::AdminAccountsDeleteRequest (required)

Return: UserLite, OpenAPI.Clients.ApiResponse
"""
function following_invalidate(_api::FollowingApi, admin_accounts_delete_request::AdminAccountsDeleteRequest; _mediaType=nothing)
    _ctx = _oacinternal_following_invalidate(_api, admin_accounts_delete_request; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function following_invalidate(_api::FollowingApi, response_stream::Channel, admin_accounts_delete_request::AdminAccountsDeleteRequest; _mediaType=nothing)
    _ctx = _oacinternal_following_invalidate(_api, admin_accounts_delete_request; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_following_requests_accept_FollowingApi = Dict{Regex,Type}(
    Regex("^" * replace("204", "x"=>".") * "\$") => Nothing,
    Regex("^" * replace("400", "x"=>".") * "\$") => Error,
    Regex("^" * replace("401", "x"=>".") * "\$") => Error,
    Regex("^" * replace("403", "x"=>".") * "\$") => Error,
    Regex("^" * replace("418", "x"=>".") * "\$") => Error,
    Regex("^" * replace("500", "x"=>".") * "\$") => Error,
)

function _oacinternal_following_requests_accept(_api::FollowingApi, admin_accounts_delete_request::AdminAccountsDeleteRequest; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "POST", _returntypes_following_requests_accept_FollowingApi, "/following/requests/accept", ["bearerAuth", ], admin_accounts_delete_request)
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? ["application/json", ] : [_mediaType])
    return _ctx
end

@doc raw"""following/requests/accept

No description provided.  **Credential required**: *Yes* / **Permission**: *write:following*

Params:
- admin_accounts_delete_request::AdminAccountsDeleteRequest (required)

Return: Nothing, OpenAPI.Clients.ApiResponse
"""
function following_requests_accept(_api::FollowingApi, admin_accounts_delete_request::AdminAccountsDeleteRequest; _mediaType=nothing)
    _ctx = _oacinternal_following_requests_accept(_api, admin_accounts_delete_request; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function following_requests_accept(_api::FollowingApi, response_stream::Channel, admin_accounts_delete_request::AdminAccountsDeleteRequest; _mediaType=nothing)
    _ctx = _oacinternal_following_requests_accept(_api, admin_accounts_delete_request; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_following_requests_cancel_FollowingApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => UserLite,
    Regex("^" * replace("400", "x"=>".") * "\$") => Error,
    Regex("^" * replace("401", "x"=>".") * "\$") => Error,
    Regex("^" * replace("403", "x"=>".") * "\$") => Error,
    Regex("^" * replace("418", "x"=>".") * "\$") => Error,
    Regex("^" * replace("500", "x"=>".") * "\$") => Error,
)

function _oacinternal_following_requests_cancel(_api::FollowingApi, admin_accounts_delete_request::AdminAccountsDeleteRequest; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "POST", _returntypes_following_requests_cancel_FollowingApi, "/following/requests/cancel", ["bearerAuth", ], admin_accounts_delete_request)
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? ["application/json", ] : [_mediaType])
    return _ctx
end

@doc raw"""following/requests/cancel

No description provided.  **Credential required**: *Yes* / **Permission**: *write:following*

Params:
- admin_accounts_delete_request::AdminAccountsDeleteRequest (required)

Return: UserLite, OpenAPI.Clients.ApiResponse
"""
function following_requests_cancel(_api::FollowingApi, admin_accounts_delete_request::AdminAccountsDeleteRequest; _mediaType=nothing)
    _ctx = _oacinternal_following_requests_cancel(_api, admin_accounts_delete_request; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function following_requests_cancel(_api::FollowingApi, response_stream::Channel, admin_accounts_delete_request::AdminAccountsDeleteRequest; _mediaType=nothing)
    _ctx = _oacinternal_following_requests_cancel(_api, admin_accounts_delete_request; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_following_requests_list_FollowingApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => Vector{FollowingRequestsList200ResponseInner},
    Regex("^" * replace("400", "x"=>".") * "\$") => Error,
    Regex("^" * replace("401", "x"=>".") * "\$") => Error,
    Regex("^" * replace("403", "x"=>".") * "\$") => Error,
    Regex("^" * replace("418", "x"=>".") * "\$") => Error,
    Regex("^" * replace("500", "x"=>".") * "\$") => Error,
)

function _oacinternal_following_requests_list(_api::FollowingApi, following_requests_list_request::FollowingRequestsListRequest; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "POST", _returntypes_following_requests_list_FollowingApi, "/following/requests/list", ["bearerAuth", ], following_requests_list_request)
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? ["application/json", ] : [_mediaType])
    return _ctx
end

@doc raw"""following/requests/list

No description provided.  **Credential required**: *Yes* / **Permission**: *read:following*

Params:
- following_requests_list_request::FollowingRequestsListRequest (required)

Return: Vector{FollowingRequestsList200ResponseInner}, OpenAPI.Clients.ApiResponse
"""
function following_requests_list(_api::FollowingApi, following_requests_list_request::FollowingRequestsListRequest; _mediaType=nothing)
    _ctx = _oacinternal_following_requests_list(_api, following_requests_list_request; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function following_requests_list(_api::FollowingApi, response_stream::Channel, following_requests_list_request::FollowingRequestsListRequest; _mediaType=nothing)
    _ctx = _oacinternal_following_requests_list(_api, following_requests_list_request; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_following_requests_reject_FollowingApi = Dict{Regex,Type}(
    Regex("^" * replace("204", "x"=>".") * "\$") => Nothing,
    Regex("^" * replace("400", "x"=>".") * "\$") => Error,
    Regex("^" * replace("401", "x"=>".") * "\$") => Error,
    Regex("^" * replace("403", "x"=>".") * "\$") => Error,
    Regex("^" * replace("418", "x"=>".") * "\$") => Error,
    Regex("^" * replace("500", "x"=>".") * "\$") => Error,
)

function _oacinternal_following_requests_reject(_api::FollowingApi, admin_accounts_delete_request::AdminAccountsDeleteRequest; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "POST", _returntypes_following_requests_reject_FollowingApi, "/following/requests/reject", ["bearerAuth", ], admin_accounts_delete_request)
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? ["application/json", ] : [_mediaType])
    return _ctx
end

@doc raw"""following/requests/reject

No description provided.  **Credential required**: *Yes* / **Permission**: *write:following*

Params:
- admin_accounts_delete_request::AdminAccountsDeleteRequest (required)

Return: Nothing, OpenAPI.Clients.ApiResponse
"""
function following_requests_reject(_api::FollowingApi, admin_accounts_delete_request::AdminAccountsDeleteRequest; _mediaType=nothing)
    _ctx = _oacinternal_following_requests_reject(_api, admin_accounts_delete_request; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function following_requests_reject(_api::FollowingApi, response_stream::Channel, admin_accounts_delete_request::AdminAccountsDeleteRequest; _mediaType=nothing)
    _ctx = _oacinternal_following_requests_reject(_api, admin_accounts_delete_request; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_following_update_FollowingApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => UserLite,
    Regex("^" * replace("400", "x"=>".") * "\$") => Error,
    Regex("^" * replace("401", "x"=>".") * "\$") => Error,
    Regex("^" * replace("403", "x"=>".") * "\$") => Error,
    Regex("^" * replace("418", "x"=>".") * "\$") => Error,
    Regex("^" * replace("429", "x"=>".") * "\$") => Error,
    Regex("^" * replace("500", "x"=>".") * "\$") => Error,
)

function _oacinternal_following_update(_api::FollowingApi, following_update_request::FollowingUpdateRequest; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "POST", _returntypes_following_update_FollowingApi, "/following/update", ["bearerAuth", ], following_update_request)
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? ["application/json", ] : [_mediaType])
    return _ctx
end

@doc raw"""following/update

No description provided.  **Credential required**: *Yes* / **Permission**: *write:following*

Params:
- following_update_request::FollowingUpdateRequest (required)

Return: UserLite, OpenAPI.Clients.ApiResponse
"""
function following_update(_api::FollowingApi, following_update_request::FollowingUpdateRequest; _mediaType=nothing)
    _ctx = _oacinternal_following_update(_api, following_update_request; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function following_update(_api::FollowingApi, response_stream::Channel, following_update_request::FollowingUpdateRequest; _mediaType=nothing)
    _ctx = _oacinternal_following_update(_api, following_update_request; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_following_update_all_FollowingApi = Dict{Regex,Type}(
    Regex("^" * replace("204", "x"=>".") * "\$") => Nothing,
    Regex("^" * replace("400", "x"=>".") * "\$") => Error,
    Regex("^" * replace("401", "x"=>".") * "\$") => Error,
    Regex("^" * replace("403", "x"=>".") * "\$") => Error,
    Regex("^" * replace("418", "x"=>".") * "\$") => Error,
    Regex("^" * replace("429", "x"=>".") * "\$") => Error,
    Regex("^" * replace("500", "x"=>".") * "\$") => Error,
)

function _oacinternal_following_update_all(_api::FollowingApi, following_update_all_request::FollowingUpdateAllRequest; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "POST", _returntypes_following_update_all_FollowingApi, "/following/update-all", ["bearerAuth", ], following_update_all_request)
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? ["application/json", ] : [_mediaType])
    return _ctx
end

@doc raw"""following/update-all

No description provided.  **Credential required**: *Yes* / **Permission**: *write:following*

Params:
- following_update_all_request::FollowingUpdateAllRequest (required)

Return: Nothing, OpenAPI.Clients.ApiResponse
"""
function following_update_all(_api::FollowingApi, following_update_all_request::FollowingUpdateAllRequest; _mediaType=nothing)
    _ctx = _oacinternal_following_update_all(_api, following_update_all_request; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function following_update_all(_api::FollowingApi, response_stream::Channel, following_update_all_request::FollowingUpdateAllRequest; _mediaType=nothing)
    _ctx = _oacinternal_following_update_all(_api, following_update_all_request; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

export following_create
export following_delete
export following_invalidate
export following_requests_accept
export following_requests_cancel
export following_requests_list
export following_requests_reject
export following_update
export following_update_all
