# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.

struct GalleryApi <: OpenAPI.APIClientImpl
    client::OpenAPI.Clients.Client
end

"""
The default API base path for APIs in `GalleryApi`.
This can be used to construct the `OpenAPI.Clients.Client` instance.
"""
basepath(::Type{ GalleryApi }) = "https://misskey.qwjyh.net/api"

const _returntypes_gallery_featured_GalleryApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => Vector{GalleryPost},
    Regex("^" * replace("400", "x"=>".") * "\$") => Error,
    Regex("^" * replace("401", "x"=>".") * "\$") => Error,
    Regex("^" * replace("403", "x"=>".") * "\$") => Error,
    Regex("^" * replace("418", "x"=>".") * "\$") => Error,
    Regex("^" * replace("500", "x"=>".") * "\$") => Error,
)

function _oacinternal_gallery_featured(_api::GalleryApi, gallery_featured_request::GalleryFeaturedRequest; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "POST", _returntypes_gallery_featured_GalleryApi, "/gallery/featured", [], gallery_featured_request)
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? ["application/json", ] : [_mediaType])
    return _ctx
end

@doc raw"""gallery/featured

No description provided.  **Credential required**: *No*

Params:
- gallery_featured_request::GalleryFeaturedRequest (required)

Return: Vector{GalleryPost}, OpenAPI.Clients.ApiResponse
"""
function gallery_featured(_api::GalleryApi, gallery_featured_request::GalleryFeaturedRequest; _mediaType=nothing)
    _ctx = _oacinternal_gallery_featured(_api, gallery_featured_request; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function gallery_featured(_api::GalleryApi, response_stream::Channel, gallery_featured_request::GalleryFeaturedRequest; _mediaType=nothing)
    _ctx = _oacinternal_gallery_featured(_api, gallery_featured_request; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_gallery_popular_GalleryApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => Vector{GalleryPost},
    Regex("^" * replace("400", "x"=>".") * "\$") => Error,
    Regex("^" * replace("401", "x"=>".") * "\$") => Error,
    Regex("^" * replace("403", "x"=>".") * "\$") => Error,
    Regex("^" * replace("418", "x"=>".") * "\$") => Error,
    Regex("^" * replace("500", "x"=>".") * "\$") => Error,
)

function _oacinternal_gallery_popular(_api::GalleryApi; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "POST", _returntypes_gallery_popular_GalleryApi, "/gallery/popular", [])
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""gallery/popular

No description provided.  **Credential required**: *No*

Params:

Return: Vector{GalleryPost}, OpenAPI.Clients.ApiResponse
"""
function gallery_popular(_api::GalleryApi; _mediaType=nothing)
    _ctx = _oacinternal_gallery_popular(_api; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function gallery_popular(_api::GalleryApi, response_stream::Channel; _mediaType=nothing)
    _ctx = _oacinternal_gallery_popular(_api; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_gallery_posts_GalleryApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => Vector{GalleryPost},
    Regex("^" * replace("400", "x"=>".") * "\$") => Error,
    Regex("^" * replace("401", "x"=>".") * "\$") => Error,
    Regex("^" * replace("403", "x"=>".") * "\$") => Error,
    Regex("^" * replace("418", "x"=>".") * "\$") => Error,
    Regex("^" * replace("500", "x"=>".") * "\$") => Error,
)

function _oacinternal_gallery_posts(_api::GalleryApi, following_requests_list_request::FollowingRequestsListRequest; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "POST", _returntypes_gallery_posts_GalleryApi, "/gallery/posts", [], following_requests_list_request)
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? ["application/json", ] : [_mediaType])
    return _ctx
end

@doc raw"""gallery/posts

No description provided.  **Credential required**: *No*

Params:
- following_requests_list_request::FollowingRequestsListRequest (required)

Return: Vector{GalleryPost}, OpenAPI.Clients.ApiResponse
"""
function gallery_posts(_api::GalleryApi, following_requests_list_request::FollowingRequestsListRequest; _mediaType=nothing)
    _ctx = _oacinternal_gallery_posts(_api, following_requests_list_request; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function gallery_posts(_api::GalleryApi, response_stream::Channel, following_requests_list_request::FollowingRequestsListRequest; _mediaType=nothing)
    _ctx = _oacinternal_gallery_posts(_api, following_requests_list_request; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_gallery_posts_create_GalleryApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => GalleryPost,
    Regex("^" * replace("400", "x"=>".") * "\$") => Error,
    Regex("^" * replace("401", "x"=>".") * "\$") => Error,
    Regex("^" * replace("403", "x"=>".") * "\$") => Error,
    Regex("^" * replace("418", "x"=>".") * "\$") => Error,
    Regex("^" * replace("429", "x"=>".") * "\$") => Error,
    Regex("^" * replace("500", "x"=>".") * "\$") => Error,
)

function _oacinternal_gallery_posts_create(_api::GalleryApi, gallery_posts_create_request::GalleryPostsCreateRequest; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "POST", _returntypes_gallery_posts_create_GalleryApi, "/gallery/posts/create", ["bearerAuth", ], gallery_posts_create_request)
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? ["application/json", ] : [_mediaType])
    return _ctx
end

@doc raw"""gallery/posts/create

No description provided.  **Credential required**: *Yes* / **Permission**: *write:gallery*

Params:
- gallery_posts_create_request::GalleryPostsCreateRequest (required)

Return: GalleryPost, OpenAPI.Clients.ApiResponse
"""
function gallery_posts_create(_api::GalleryApi, gallery_posts_create_request::GalleryPostsCreateRequest; _mediaType=nothing)
    _ctx = _oacinternal_gallery_posts_create(_api, gallery_posts_create_request; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function gallery_posts_create(_api::GalleryApi, response_stream::Channel, gallery_posts_create_request::GalleryPostsCreateRequest; _mediaType=nothing)
    _ctx = _oacinternal_gallery_posts_create(_api, gallery_posts_create_request; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_gallery_posts_delete_GalleryApi = Dict{Regex,Type}(
    Regex("^" * replace("204", "x"=>".") * "\$") => Nothing,
    Regex("^" * replace("400", "x"=>".") * "\$") => Error,
    Regex("^" * replace("401", "x"=>".") * "\$") => Error,
    Regex("^" * replace("403", "x"=>".") * "\$") => Error,
    Regex("^" * replace("418", "x"=>".") * "\$") => Error,
    Regex("^" * replace("500", "x"=>".") * "\$") => Error,
)

function _oacinternal_gallery_posts_delete(_api::GalleryApi, gallery_posts_delete_request::GalleryPostsDeleteRequest; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "POST", _returntypes_gallery_posts_delete_GalleryApi, "/gallery/posts/delete", ["bearerAuth", ], gallery_posts_delete_request)
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? ["application/json", ] : [_mediaType])
    return _ctx
end

@doc raw"""gallery/posts/delete

No description provided.  **Credential required**: *Yes* / **Permission**: *write:gallery*

Params:
- gallery_posts_delete_request::GalleryPostsDeleteRequest (required)

Return: Nothing, OpenAPI.Clients.ApiResponse
"""
function gallery_posts_delete(_api::GalleryApi, gallery_posts_delete_request::GalleryPostsDeleteRequest; _mediaType=nothing)
    _ctx = _oacinternal_gallery_posts_delete(_api, gallery_posts_delete_request; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function gallery_posts_delete(_api::GalleryApi, response_stream::Channel, gallery_posts_delete_request::GalleryPostsDeleteRequest; _mediaType=nothing)
    _ctx = _oacinternal_gallery_posts_delete(_api, gallery_posts_delete_request; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_gallery_posts_like_GalleryApi = Dict{Regex,Type}(
    Regex("^" * replace("204", "x"=>".") * "\$") => Nothing,
    Regex("^" * replace("400", "x"=>".") * "\$") => Error,
    Regex("^" * replace("401", "x"=>".") * "\$") => Error,
    Regex("^" * replace("403", "x"=>".") * "\$") => Error,
    Regex("^" * replace("418", "x"=>".") * "\$") => Error,
    Regex("^" * replace("500", "x"=>".") * "\$") => Error,
)

function _oacinternal_gallery_posts_like(_api::GalleryApi, gallery_posts_delete_request::GalleryPostsDeleteRequest; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "POST", _returntypes_gallery_posts_like_GalleryApi, "/gallery/posts/like", ["bearerAuth", ], gallery_posts_delete_request)
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? ["application/json", ] : [_mediaType])
    return _ctx
end

@doc raw"""gallery/posts/like

No description provided.  **Credential required**: *Yes* / **Permission**: *write:gallery-likes*

Params:
- gallery_posts_delete_request::GalleryPostsDeleteRequest (required)

Return: Nothing, OpenAPI.Clients.ApiResponse
"""
function gallery_posts_like(_api::GalleryApi, gallery_posts_delete_request::GalleryPostsDeleteRequest; _mediaType=nothing)
    _ctx = _oacinternal_gallery_posts_like(_api, gallery_posts_delete_request; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function gallery_posts_like(_api::GalleryApi, response_stream::Channel, gallery_posts_delete_request::GalleryPostsDeleteRequest; _mediaType=nothing)
    _ctx = _oacinternal_gallery_posts_like(_api, gallery_posts_delete_request; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_gallery_posts_show_GalleryApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => GalleryPost,
    Regex("^" * replace("400", "x"=>".") * "\$") => Error,
    Regex("^" * replace("401", "x"=>".") * "\$") => Error,
    Regex("^" * replace("403", "x"=>".") * "\$") => Error,
    Regex("^" * replace("418", "x"=>".") * "\$") => Error,
    Regex("^" * replace("500", "x"=>".") * "\$") => Error,
)

function _oacinternal_gallery_posts_show(_api::GalleryApi, gallery_posts_delete_request::GalleryPostsDeleteRequest; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "POST", _returntypes_gallery_posts_show_GalleryApi, "/gallery/posts/show", [], gallery_posts_delete_request)
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? ["application/json", ] : [_mediaType])
    return _ctx
end

@doc raw"""gallery/posts/show

No description provided.  **Credential required**: *No*

Params:
- gallery_posts_delete_request::GalleryPostsDeleteRequest (required)

Return: GalleryPost, OpenAPI.Clients.ApiResponse
"""
function gallery_posts_show(_api::GalleryApi, gallery_posts_delete_request::GalleryPostsDeleteRequest; _mediaType=nothing)
    _ctx = _oacinternal_gallery_posts_show(_api, gallery_posts_delete_request; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function gallery_posts_show(_api::GalleryApi, response_stream::Channel, gallery_posts_delete_request::GalleryPostsDeleteRequest; _mediaType=nothing)
    _ctx = _oacinternal_gallery_posts_show(_api, gallery_posts_delete_request; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_gallery_posts_unlike_GalleryApi = Dict{Regex,Type}(
    Regex("^" * replace("204", "x"=>".") * "\$") => Nothing,
    Regex("^" * replace("400", "x"=>".") * "\$") => Error,
    Regex("^" * replace("401", "x"=>".") * "\$") => Error,
    Regex("^" * replace("403", "x"=>".") * "\$") => Error,
    Regex("^" * replace("418", "x"=>".") * "\$") => Error,
    Regex("^" * replace("500", "x"=>".") * "\$") => Error,
)

function _oacinternal_gallery_posts_unlike(_api::GalleryApi, gallery_posts_delete_request::GalleryPostsDeleteRequest; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "POST", _returntypes_gallery_posts_unlike_GalleryApi, "/gallery/posts/unlike", ["bearerAuth", ], gallery_posts_delete_request)
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? ["application/json", ] : [_mediaType])
    return _ctx
end

@doc raw"""gallery/posts/unlike

No description provided.  **Credential required**: *Yes* / **Permission**: *write:gallery-likes*

Params:
- gallery_posts_delete_request::GalleryPostsDeleteRequest (required)

Return: Nothing, OpenAPI.Clients.ApiResponse
"""
function gallery_posts_unlike(_api::GalleryApi, gallery_posts_delete_request::GalleryPostsDeleteRequest; _mediaType=nothing)
    _ctx = _oacinternal_gallery_posts_unlike(_api, gallery_posts_delete_request; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function gallery_posts_unlike(_api::GalleryApi, response_stream::Channel, gallery_posts_delete_request::GalleryPostsDeleteRequest; _mediaType=nothing)
    _ctx = _oacinternal_gallery_posts_unlike(_api, gallery_posts_delete_request; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_gallery_posts_update_GalleryApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => GalleryPost,
    Regex("^" * replace("400", "x"=>".") * "\$") => Error,
    Regex("^" * replace("401", "x"=>".") * "\$") => Error,
    Regex("^" * replace("403", "x"=>".") * "\$") => Error,
    Regex("^" * replace("418", "x"=>".") * "\$") => Error,
    Regex("^" * replace("429", "x"=>".") * "\$") => Error,
    Regex("^" * replace("500", "x"=>".") * "\$") => Error,
)

function _oacinternal_gallery_posts_update(_api::GalleryApi, gallery_posts_update_request::GalleryPostsUpdateRequest; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "POST", _returntypes_gallery_posts_update_GalleryApi, "/gallery/posts/update", ["bearerAuth", ], gallery_posts_update_request)
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? ["application/json", ] : [_mediaType])
    return _ctx
end

@doc raw"""gallery/posts/update

No description provided.  **Credential required**: *Yes* / **Permission**: *write:gallery*

Params:
- gallery_posts_update_request::GalleryPostsUpdateRequest (required)

Return: GalleryPost, OpenAPI.Clients.ApiResponse
"""
function gallery_posts_update(_api::GalleryApi, gallery_posts_update_request::GalleryPostsUpdateRequest; _mediaType=nothing)
    _ctx = _oacinternal_gallery_posts_update(_api, gallery_posts_update_request; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function gallery_posts_update(_api::GalleryApi, response_stream::Channel, gallery_posts_update_request::GalleryPostsUpdateRequest; _mediaType=nothing)
    _ctx = _oacinternal_gallery_posts_update(_api, gallery_posts_update_request; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

export gallery_featured
export gallery_popular
export gallery_posts
export gallery_posts_create
export gallery_posts_delete
export gallery_posts_like
export gallery_posts_show
export gallery_posts_unlike
export gallery_posts_update
