# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""Notification_oneOf_8

    NotificationOneOf8(;
        id=nothing,
        createdAt=nothing,
        type=nothing,
        user=nothing,
        userId=nothing,
    )

    - id::String
    - createdAt::ZonedDateTime
    - type::String
    - user::UserLite
    - userId::String
"""
Base.@kwdef mutable struct NotificationOneOf8 <: OpenAPI.APIModel
    id::Union{Nothing, String} = nothing
    createdAt::Union{Nothing, ZonedDateTime} = nothing
    type::Union{Nothing, String} = nothing
    user = nothing # spec type: Union{ Nothing, UserLite }
    userId::Union{Nothing, String} = nothing

    function NotificationOneOf8(id, createdAt, type, user, userId, )
        OpenAPI.validate_property(NotificationOneOf8, Symbol("id"), id)
        OpenAPI.validate_property(NotificationOneOf8, Symbol("createdAt"), createdAt)
        OpenAPI.validate_property(NotificationOneOf8, Symbol("type"), type)
        OpenAPI.validate_property(NotificationOneOf8, Symbol("user"), user)
        OpenAPI.validate_property(NotificationOneOf8, Symbol("userId"), userId)
        return new(id, createdAt, type, user, userId, )
    end
end # type NotificationOneOf8

const _property_types_NotificationOneOf8 = Dict{Symbol,String}(Symbol("id")=>"String", Symbol("createdAt")=>"ZonedDateTime", Symbol("type")=>"String", Symbol("user")=>"UserLite", Symbol("userId")=>"String", )
OpenAPI.property_type(::Type{ NotificationOneOf8 }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_NotificationOneOf8[name]))}

function check_required(o::NotificationOneOf8)
    o.id === nothing && (return false)
    o.createdAt === nothing && (return false)
    o.type === nothing && (return false)
    o.user === nothing && (return false)
    o.userId === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ NotificationOneOf8 }, name::Symbol, val)
    if name === Symbol("id")
        OpenAPI.validate_param(name, "NotificationOneOf8", :format, val, "id")
    end
    if name === Symbol("createdAt")
        OpenAPI.validate_param(name, "NotificationOneOf8", :format, val, "date-time")
    end
    if name === Symbol("type")
        OpenAPI.validate_param(name, "NotificationOneOf8", :enum, val, ["receiveFollowRequest"])
    end
    if name === Symbol("userId")
        OpenAPI.validate_param(name, "NotificationOneOf8", :format, val, "id")
    end
end
