# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""following___requests___list_request

    FollowingRequestsListRequest(;
        sinceId=nothing,
        untilId=nothing,
        limit=10,
    )

    - sinceId::String
    - untilId::String
    - limit::Int64
"""
Base.@kwdef mutable struct FollowingRequestsListRequest <: OpenAPI.APIModel
    sinceId::Union{Nothing, String} = nothing
    untilId::Union{Nothing, String} = nothing
    limit::Union{Nothing, Int64} = 10

    function FollowingRequestsListRequest(sinceId, untilId, limit, )
        OpenAPI.validate_property(FollowingRequestsListRequest, Symbol("sinceId"), sinceId)
        OpenAPI.validate_property(FollowingRequestsListRequest, Symbol("untilId"), untilId)
        OpenAPI.validate_property(FollowingRequestsListRequest, Symbol("limit"), limit)
        return new(sinceId, untilId, limit, )
    end
end # type FollowingRequestsListRequest

const _property_types_FollowingRequestsListRequest = Dict{Symbol,String}(Symbol("sinceId")=>"String", Symbol("untilId")=>"String", Symbol("limit")=>"Int64", )
OpenAPI.property_type(::Type{ FollowingRequestsListRequest }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_FollowingRequestsListRequest[name]))}

function check_required(o::FollowingRequestsListRequest)
    true
end

function OpenAPI.validate_property(::Type{ FollowingRequestsListRequest }, name::Symbol, val)
    if name === Symbol("sinceId")
        OpenAPI.validate_param(name, "FollowingRequestsListRequest", :format, val, "misskey:id")
    end
    if name === Symbol("untilId")
        OpenAPI.validate_param(name, "FollowingRequestsListRequest", :format, val, "misskey:id")
    end
    if name === Symbol("limit")
        OpenAPI.validate_param(name, "FollowingRequestsListRequest", :maximum, val, 100, false)
        OpenAPI.validate_param(name, "FollowingRequestsListRequest", :minimum, val, 1, false)
    end
end
