# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.



@doc raw"""admin___show_user_200_response_mutedWords_inner

    AdminShowUser200ResponseMutedWordsInner(; value=nothing)
"""
mutable struct AdminShowUser200ResponseMutedWordsInner <: OpenAPI.AnyOfAPIModel
    value::Any # Union{ String, Vector{String} }
    AdminShowUser200ResponseMutedWordsInner() = new()
    AdminShowUser200ResponseMutedWordsInner(value) = new(value)
end # type AdminShowUser200ResponseMutedWordsInner

function OpenAPI.property_type(::Type{ AdminShowUser200ResponseMutedWordsInner }, name::Symbol, json::Dict{String,Any})
    
    # no discriminator specified, can't determine the exact type
    return fieldtype(AdminShowUser200ResponseMutedWordsInner, name)
end
