# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""i___2fa___done_200_response

    I2faDone200Response(;
        backupCodes=nothing,
    )

    - backupCodes::Vector{String}
"""
Base.@kwdef mutable struct I2faDone200Response <: OpenAPI.APIModel
    backupCodes::Union{Nothing, Vector{String}} = nothing

    function I2faDone200Response(backupCodes, )
        OpenAPI.validate_property(I2faDone200Response, Symbol("backupCodes"), backupCodes)
        return new(backupCodes, )
    end
end # type I2faDone200Response

const _property_types_I2faDone200Response = Dict{Symbol,String}(Symbol("backupCodes")=>"Vector{String}", )
OpenAPI.property_type(::Type{ I2faDone200Response }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_I2faDone200Response[name]))}

function check_required(o::I2faDone200Response)
    o.backupCodes === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ I2faDone200Response }, name::Symbol, val)
end
