# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""reversi___show_game_request

    ReversiShowGameRequest(;
        gameId=nothing,
    )

    - gameId::String
"""
Base.@kwdef mutable struct ReversiShowGameRequest <: OpenAPI.APIModel
    gameId::Union{Nothing, String} = nothing

    function ReversiShowGameRequest(gameId, )
        OpenAPI.validate_property(ReversiShowGameRequest, Symbol("gameId"), gameId)
        return new(gameId, )
    end
end # type ReversiShowGameRequest

const _property_types_ReversiShowGameRequest = Dict{Symbol,String}(Symbol("gameId")=>"String", )
OpenAPI.property_type(::Type{ ReversiShowGameRequest }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ReversiShowGameRequest[name]))}

function check_required(o::ReversiShowGameRequest)
    o.gameId === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ ReversiShowGameRequest }, name::Symbol, val)
    if name === Symbol("gameId")
        OpenAPI.validate_param(name, "ReversiShowGameRequest", :format, val, "misskey:id")
    end
end
