# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""federation___followers_request

    FederationFollowersRequest(;
        host=nothing,
        sinceId=nothing,
        untilId=nothing,
        limit=10,
    )

    - host::String
    - sinceId::String
    - untilId::String
    - limit::Int64
"""
Base.@kwdef mutable struct FederationFollowersRequest <: OpenAPI.APIModel
    host::Union{Nothing, String} = nothing
    sinceId::Union{Nothing, String} = nothing
    untilId::Union{Nothing, String} = nothing
    limit::Union{Nothing, Int64} = 10

    function FederationFollowersRequest(host, sinceId, untilId, limit, )
        OpenAPI.validate_property(FederationFollowersRequest, Symbol("host"), host)
        OpenAPI.validate_property(FederationFollowersRequest, Symbol("sinceId"), sinceId)
        OpenAPI.validate_property(FederationFollowersRequest, Symbol("untilId"), untilId)
        OpenAPI.validate_property(FederationFollowersRequest, Symbol("limit"), limit)
        return new(host, sinceId, untilId, limit, )
    end
end # type FederationFollowersRequest

const _property_types_FederationFollowersRequest = Dict{Symbol,String}(Symbol("host")=>"String", Symbol("sinceId")=>"String", Symbol("untilId")=>"String", Symbol("limit")=>"Int64", )
OpenAPI.property_type(::Type{ FederationFollowersRequest }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_FederationFollowersRequest[name]))}

function check_required(o::FederationFollowersRequest)
    o.host === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ FederationFollowersRequest }, name::Symbol, val)
    if name === Symbol("sinceId")
        OpenAPI.validate_param(name, "FederationFollowersRequest", :format, val, "misskey:id")
    end
    if name === Symbol("untilId")
        OpenAPI.validate_param(name, "FederationFollowersRequest", :format, val, "misskey:id")
    end
    if name === Symbol("limit")
        OpenAPI.validate_param(name, "FederationFollowersRequest", :maximum, val, 100, false)
        OpenAPI.validate_param(name, "FederationFollowersRequest", :minimum, val, 1, false)
    end
end
