# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""admin___emoji___copy_200_response

    AdminEmojiCopy200Response(;
        id=nothing,
    )

    - id::String
"""
Base.@kwdef mutable struct AdminEmojiCopy200Response <: OpenAPI.APIModel
    id::Union{Nothing, String} = nothing

    function AdminEmojiCopy200Response(id, )
        OpenAPI.validate_property(AdminEmojiCopy200Response, Symbol("id"), id)
        return new(id, )
    end
end # type AdminEmojiCopy200Response

const _property_types_AdminEmojiCopy200Response = Dict{Symbol,String}(Symbol("id")=>"String", )
OpenAPI.property_type(::Type{ AdminEmojiCopy200Response }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_AdminEmojiCopy200Response[name]))}

function check_required(o::AdminEmojiCopy200Response)
    o.id === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ AdminEmojiCopy200Response }, name::Symbol, val)
    if name === Symbol("id")
        OpenAPI.validate_param(name, "AdminEmojiCopy200Response", :format, val, "id")
    end
end
