# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""notes___state_200_response

    NotesState200Response(;
        isFavorited=nothing,
        isMutedThread=nothing,
    )

    - isFavorited::Bool
    - isMutedThread::Bool
"""
Base.@kwdef mutable struct NotesState200Response <: OpenAPI.APIModel
    isFavorited::Union{Nothing, Bool} = nothing
    isMutedThread::Union{Nothing, Bool} = nothing

    function NotesState200Response(isFavorited, isMutedThread, )
        OpenAPI.validate_property(NotesState200Response, Symbol("isFavorited"), isFavorited)
        OpenAPI.validate_property(NotesState200Response, Symbol("isMutedThread"), isMutedThread)
        return new(isFavorited, isMutedThread, )
    end
end # type NotesState200Response

const _property_types_NotesState200Response = Dict{Symbol,String}(Symbol("isFavorited")=>"Bool", Symbol("isMutedThread")=>"Bool", )
OpenAPI.property_type(::Type{ NotesState200Response }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_NotesState200Response[name]))}

function check_required(o::NotesState200Response)
    o.isFavorited === nothing && (return false)
    o.isMutedThread === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ NotesState200Response }, name::Symbol, val)
end
