# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""admin___federation___delete_all_files_request

    AdminFederationDeleteAllFilesRequest(;
        host=nothing,
    )

    - host::String
"""
Base.@kwdef mutable struct AdminFederationDeleteAllFilesRequest <: OpenAPI.APIModel
    host::Union{Nothing, String} = nothing

    function AdminFederationDeleteAllFilesRequest(host, )
        OpenAPI.validate_property(AdminFederationDeleteAllFilesRequest, Symbol("host"), host)
        return new(host, )
    end
end # type AdminFederationDeleteAllFilesRequest

const _property_types_AdminFederationDeleteAllFilesRequest = Dict{Symbol,String}(Symbol("host")=>"String", )
OpenAPI.property_type(::Type{ AdminFederationDeleteAllFilesRequest }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_AdminFederationDeleteAllFilesRequest[name]))}

function check_required(o::AdminFederationDeleteAllFilesRequest)
    o.host === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ AdminFederationDeleteAllFilesRequest }, name::Symbol, val)
end
