# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""admin___server_info_200_response_mem

    AdminServerInfo200ResponseMem(;
        total=nothing,
    )

    - total::Float64
"""
Base.@kwdef mutable struct AdminServerInfo200ResponseMem <: OpenAPI.APIModel
    total::Union{Nothing, Float64} = nothing

    function AdminServerInfo200ResponseMem(total, )
        OpenAPI.validate_property(AdminServerInfo200ResponseMem, Symbol("total"), total)
        return new(total, )
    end
end # type AdminServerInfo200ResponseMem

const _property_types_AdminServerInfo200ResponseMem = Dict{Symbol,String}(Symbol("total")=>"Float64", )
OpenAPI.property_type(::Type{ AdminServerInfo200ResponseMem }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_AdminServerInfo200ResponseMem[name]))}

function check_required(o::AdminServerInfo200ResponseMem)
    o.total === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ AdminServerInfo200ResponseMem }, name::Symbol, val)
    if name === Symbol("total")
        OpenAPI.validate_param(name, "AdminServerInfo200ResponseMem", :format, val, "bytes")
    end
end
