# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""EmojiDetailed

    EmojiDetailed(;
        id=nothing,
        aliases=nothing,
        name=nothing,
        category=nothing,
        host=nothing,
        url=nothing,
        license=nothing,
        isSensitive=nothing,
        localOnly=nothing,
        roleIdsThatCanBeUsedThisEmojiAsReaction=nothing,
    )

    - id::String
    - aliases::Vector{String}
    - name::String
    - category::String
    - host::String : The local host is represented with &#x60;null&#x60;.
    - url::String
    - license::String
    - isSensitive::Bool
    - localOnly::Bool
    - roleIdsThatCanBeUsedThisEmojiAsReaction::Vector{String}
"""
Base.@kwdef mutable struct EmojiDetailed <: OpenAPI.APIModel
    id::Union{Nothing, String} = nothing
    aliases::Union{Nothing, Vector{String}} = nothing
    name::Union{Nothing, String} = nothing
    category::Union{Nothing, String} = nothing
    host::Union{Nothing, String} = nothing
    url::Union{Nothing, String} = nothing
    license::Union{Nothing, String} = nothing
    isSensitive::Union{Nothing, Bool} = nothing
    localOnly::Union{Nothing, Bool} = nothing
    roleIdsThatCanBeUsedThisEmojiAsReaction::Union{Nothing, Vector{String}} = nothing

    function EmojiDetailed(id, aliases, name, category, host, url, license, isSensitive, localOnly, roleIdsThatCanBeUsedThisEmojiAsReaction, )
        OpenAPI.validate_property(EmojiDetailed, Symbol("id"), id)
        OpenAPI.validate_property(EmojiDetailed, Symbol("aliases"), aliases)
        OpenAPI.validate_property(EmojiDetailed, Symbol("name"), name)
        OpenAPI.validate_property(EmojiDetailed, Symbol("category"), category)
        OpenAPI.validate_property(EmojiDetailed, Symbol("host"), host)
        OpenAPI.validate_property(EmojiDetailed, Symbol("url"), url)
        OpenAPI.validate_property(EmojiDetailed, Symbol("license"), license)
        OpenAPI.validate_property(EmojiDetailed, Symbol("isSensitive"), isSensitive)
        OpenAPI.validate_property(EmojiDetailed, Symbol("localOnly"), localOnly)
        OpenAPI.validate_property(EmojiDetailed, Symbol("roleIdsThatCanBeUsedThisEmojiAsReaction"), roleIdsThatCanBeUsedThisEmojiAsReaction)
        return new(id, aliases, name, category, host, url, license, isSensitive, localOnly, roleIdsThatCanBeUsedThisEmojiAsReaction, )
    end
end # type EmojiDetailed

const _property_types_EmojiDetailed = Dict{Symbol,String}(Symbol("id")=>"String", Symbol("aliases")=>"Vector{String}", Symbol("name")=>"String", Symbol("category")=>"String", Symbol("host")=>"String", Symbol("url")=>"String", Symbol("license")=>"String", Symbol("isSensitive")=>"Bool", Symbol("localOnly")=>"Bool", Symbol("roleIdsThatCanBeUsedThisEmojiAsReaction")=>"Vector{String}", )
OpenAPI.property_type(::Type{ EmojiDetailed }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_EmojiDetailed[name]))}

function check_required(o::EmojiDetailed)
    o.id === nothing && (return false)
    o.aliases === nothing && (return false)
    o.name === nothing && (return false)
    o.category === nothing && (return false)
    o.host === nothing && (return false)
    o.url === nothing && (return false)
    o.license === nothing && (return false)
    o.isSensitive === nothing && (return false)
    o.localOnly === nothing && (return false)
    o.roleIdsThatCanBeUsedThisEmojiAsReaction === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ EmojiDetailed }, name::Symbol, val)
    if name === Symbol("id")
        OpenAPI.validate_param(name, "EmojiDetailed", :format, val, "id")
    end
end
