# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""get_avatar_decorations_200_response_inner

    GetAvatarDecorations200ResponseInner(;
        id=nothing,
        name=nothing,
        description=nothing,
        url=nothing,
        roleIdsThatCanBeUsedThisDecoration=nothing,
    )

    - id::String
    - name::String
    - description::String
    - url::String
    - roleIdsThatCanBeUsedThisDecoration::Vector{String}
"""
Base.@kwdef mutable struct GetAvatarDecorations200ResponseInner <: OpenAPI.APIModel
    id::Union{Nothing, String} = nothing
    name::Union{Nothing, String} = nothing
    description::Union{Nothing, String} = nothing
    url::Union{Nothing, String} = nothing
    roleIdsThatCanBeUsedThisDecoration::Union{Nothing, Vector{String}} = nothing

    function GetAvatarDecorations200ResponseInner(id, name, description, url, roleIdsThatCanBeUsedThisDecoration, )
        OpenAPI.validate_property(GetAvatarDecorations200ResponseInner, Symbol("id"), id)
        OpenAPI.validate_property(GetAvatarDecorations200ResponseInner, Symbol("name"), name)
        OpenAPI.validate_property(GetAvatarDecorations200ResponseInner, Symbol("description"), description)
        OpenAPI.validate_property(GetAvatarDecorations200ResponseInner, Symbol("url"), url)
        OpenAPI.validate_property(GetAvatarDecorations200ResponseInner, Symbol("roleIdsThatCanBeUsedThisDecoration"), roleIdsThatCanBeUsedThisDecoration)
        return new(id, name, description, url, roleIdsThatCanBeUsedThisDecoration, )
    end
end # type GetAvatarDecorations200ResponseInner

const _property_types_GetAvatarDecorations200ResponseInner = Dict{Symbol,String}(Symbol("id")=>"String", Symbol("name")=>"String", Symbol("description")=>"String", Symbol("url")=>"String", Symbol("roleIdsThatCanBeUsedThisDecoration")=>"Vector{String}", )
OpenAPI.property_type(::Type{ GetAvatarDecorations200ResponseInner }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_GetAvatarDecorations200ResponseInner[name]))}

function check_required(o::GetAvatarDecorations200ResponseInner)
    o.id === nothing && (return false)
    o.name === nothing && (return false)
    o.description === nothing && (return false)
    o.url === nothing && (return false)
    o.roleIdsThatCanBeUsedThisDecoration === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ GetAvatarDecorations200ResponseInner }, name::Symbol, val)
    if name === Symbol("id")
        OpenAPI.validate_param(name, "GetAvatarDecorations200ResponseInner", :format, val, "id")
    end
end
