# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""auth___session___userkey_request

    AuthSessionUserkeyRequest(;
        appSecret=nothing,
        token=nothing,
    )

    - appSecret::String
    - token::String
"""
Base.@kwdef mutable struct AuthSessionUserkeyRequest <: OpenAPI.APIModel
    appSecret::Union{Nothing, String} = nothing
    token::Union{Nothing, String} = nothing

    function AuthSessionUserkeyRequest(appSecret, token, )
        OpenAPI.validate_property(AuthSessionUserkeyRequest, Symbol("appSecret"), appSecret)
        OpenAPI.validate_property(AuthSessionUserkeyRequest, Symbol("token"), token)
        return new(appSecret, token, )
    end
end # type AuthSessionUserkeyRequest

const _property_types_AuthSessionUserkeyRequest = Dict{Symbol,String}(Symbol("appSecret")=>"String", Symbol("token")=>"String", )
OpenAPI.property_type(::Type{ AuthSessionUserkeyRequest }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_AuthSessionUserkeyRequest[name]))}

function check_required(o::AuthSessionUserkeyRequest)
    o.appSecret === nothing && (return false)
    o.token === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ AuthSessionUserkeyRequest }, name::Symbol, val)
end
