# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""Role

    Role(;
        id=nothing,
        name=nothing,
        color=nothing,
        iconUrl=nothing,
        description=nothing,
        isModerator=nothing,
        isAdministrator=nothing,
        displayOrder=nothing,
        createdAt=nothing,
        updatedAt=nothing,
        target=nothing,
        condFormula=nothing,
        isPublic=nothing,
        isExplorable=nothing,
        asBadge=nothing,
        canEditMembersByModerator=nothing,
        policies=nothing,
        usersCount=nothing,
    )

    - id::String
    - name::String
    - color::String
    - iconUrl::String
    - description::String
    - isModerator::Bool
    - isAdministrator::Bool
    - displayOrder::Int64
    - createdAt::ZonedDateTime
    - updatedAt::ZonedDateTime
    - target::String
    - condFormula::Any
    - isPublic::Bool
    - isExplorable::Bool
    - asBadge::Bool
    - canEditMembersByModerator::Bool
    - policies::Any
    - usersCount::Int64
"""
Base.@kwdef mutable struct Role <: OpenAPI.APIModel
    id::Union{Nothing, String} = nothing
    name::Union{Nothing, String} = nothing
    color::Union{Nothing, String} = nothing
    iconUrl::Union{Nothing, String} = nothing
    description::Union{Nothing, String} = nothing
    isModerator::Union{Nothing, Bool} = nothing
    isAdministrator::Union{Nothing, Bool} = nothing
    displayOrder::Union{Nothing, Int64} = nothing
    createdAt::Union{Nothing, ZonedDateTime} = nothing
    updatedAt::Union{Nothing, ZonedDateTime} = nothing
    target::Union{Nothing, String} = nothing
    condFormula::Union{Nothing, Any} = nothing
    isPublic::Union{Nothing, Bool} = nothing
    isExplorable::Union{Nothing, Bool} = nothing
    asBadge::Union{Nothing, Bool} = nothing
    canEditMembersByModerator::Union{Nothing, Bool} = nothing
    policies::Union{Nothing, Any} = nothing
    usersCount::Union{Nothing, Int64} = nothing

    function Role(id, name, color, iconUrl, description, isModerator, isAdministrator, displayOrder, createdAt, updatedAt, target, condFormula, isPublic, isExplorable, asBadge, canEditMembersByModerator, policies, usersCount, )
        OpenAPI.validate_property(Role, Symbol("id"), id)
        OpenAPI.validate_property(Role, Symbol("name"), name)
        OpenAPI.validate_property(Role, Symbol("color"), color)
        OpenAPI.validate_property(Role, Symbol("iconUrl"), iconUrl)
        OpenAPI.validate_property(Role, Symbol("description"), description)
        OpenAPI.validate_property(Role, Symbol("isModerator"), isModerator)
        OpenAPI.validate_property(Role, Symbol("isAdministrator"), isAdministrator)
        OpenAPI.validate_property(Role, Symbol("displayOrder"), displayOrder)
        OpenAPI.validate_property(Role, Symbol("createdAt"), createdAt)
        OpenAPI.validate_property(Role, Symbol("updatedAt"), updatedAt)
        OpenAPI.validate_property(Role, Symbol("target"), target)
        OpenAPI.validate_property(Role, Symbol("condFormula"), condFormula)
        OpenAPI.validate_property(Role, Symbol("isPublic"), isPublic)
        OpenAPI.validate_property(Role, Symbol("isExplorable"), isExplorable)
        OpenAPI.validate_property(Role, Symbol("asBadge"), asBadge)
        OpenAPI.validate_property(Role, Symbol("canEditMembersByModerator"), canEditMembersByModerator)
        OpenAPI.validate_property(Role, Symbol("policies"), policies)
        OpenAPI.validate_property(Role, Symbol("usersCount"), usersCount)
        return new(id, name, color, iconUrl, description, isModerator, isAdministrator, displayOrder, createdAt, updatedAt, target, condFormula, isPublic, isExplorable, asBadge, canEditMembersByModerator, policies, usersCount, )
    end
end # type Role

const _property_types_Role = Dict{Symbol,String}(Symbol("id")=>"String", Symbol("name")=>"String", Symbol("color")=>"String", Symbol("iconUrl")=>"String", Symbol("description")=>"String", Symbol("isModerator")=>"Bool", Symbol("isAdministrator")=>"Bool", Symbol("displayOrder")=>"Int64", Symbol("createdAt")=>"ZonedDateTime", Symbol("updatedAt")=>"ZonedDateTime", Symbol("target")=>"String", Symbol("condFormula")=>"Any", Symbol("isPublic")=>"Bool", Symbol("isExplorable")=>"Bool", Symbol("asBadge")=>"Bool", Symbol("canEditMembersByModerator")=>"Bool", Symbol("policies")=>"Any", Symbol("usersCount")=>"Int64", )
OpenAPI.property_type(::Type{ Role }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_Role[name]))}

function check_required(o::Role)
    o.id === nothing && (return false)
    o.name === nothing && (return false)
    o.color === nothing && (return false)
    o.iconUrl === nothing && (return false)
    o.description === nothing && (return false)
    o.isModerator === nothing && (return false)
    o.isAdministrator === nothing && (return false)
    o.displayOrder === nothing && (return false)
    o.createdAt === nothing && (return false)
    o.updatedAt === nothing && (return false)
    o.target === nothing && (return false)
    o.condFormula === nothing && (return false)
    o.isPublic === nothing && (return false)
    o.isExplorable === nothing && (return false)
    o.asBadge === nothing && (return false)
    o.canEditMembersByModerator === nothing && (return false)
    o.policies === nothing && (return false)
    o.usersCount === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ Role }, name::Symbol, val)
    if name === Symbol("id")
        OpenAPI.validate_param(name, "Role", :format, val, "id")
    end
    if name === Symbol("createdAt")
        OpenAPI.validate_param(name, "Role", :format, val, "date-time")
    end
    if name === Symbol("updatedAt")
        OpenAPI.validate_param(name, "Role", :format, val, "date-time")
    end
    if name === Symbol("target")
        OpenAPI.validate_param(name, "Role", :enum, val, ["manual", "conditional"])
    end
end
