# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""charts___user___reactions_200_response

    ChartsUserReactions200Response(;
        var"local"=nothing,
        remote=nothing,
    )

    - var"local"::ChartsUserReactions200ResponseLocal
    - remote::ChartsUserReactions200ResponseLocal
"""
Base.@kwdef mutable struct ChartsUserReactions200Response <: OpenAPI.APIModel
    var"local" = nothing # spec type: Union{ Nothing, ChartsUserReactions200ResponseLocal }
    remote = nothing # spec type: Union{ Nothing, ChartsUserReactions200ResponseLocal }

    function ChartsUserReactions200Response(var"local", remote, )
        OpenAPI.validate_property(ChartsUserReactions200Response, Symbol("local"), var"local")
        OpenAPI.validate_property(ChartsUserReactions200Response, Symbol("remote"), remote)
        return new(var"local", remote, )
    end
end # type ChartsUserReactions200Response

const _property_types_ChartsUserReactions200Response = Dict{Symbol,String}(Symbol("local")=>"ChartsUserReactions200ResponseLocal", Symbol("remote")=>"ChartsUserReactions200ResponseLocal", )
OpenAPI.property_type(::Type{ ChartsUserReactions200Response }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ChartsUserReactions200Response[name]))}

function check_required(o::ChartsUserReactions200Response)
    o.var"local" === nothing && (return false)
    o.remote === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ ChartsUserReactions200Response }, name::Symbol, val)
end
