# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""channels___follow_request

    ChannelsFollowRequest(;
        channelId=nothing,
    )

    - channelId::String
"""
Base.@kwdef mutable struct ChannelsFollowRequest <: OpenAPI.APIModel
    channelId::Union{Nothing, String} = nothing

    function ChannelsFollowRequest(channelId, )
        OpenAPI.validate_property(ChannelsFollowRequest, Symbol("channelId"), channelId)
        return new(channelId, )
    end
end # type ChannelsFollowRequest

const _property_types_ChannelsFollowRequest = Dict{Symbol,String}(Symbol("channelId")=>"String", )
OpenAPI.property_type(::Type{ ChannelsFollowRequest }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ChannelsFollowRequest[name]))}

function check_required(o::ChannelsFollowRequest)
    o.channelId === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ ChannelsFollowRequest }, name::Symbol, val)
    if name === Symbol("channelId")
        OpenAPI.validate_param(name, "ChannelsFollowRequest", :format, val, "misskey:id")
    end
end
