# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""admin___accounts___create_200_response

    AdminAccountsCreate200Response(;
        token=nothing,
    )

    - token::String
"""
Base.@kwdef mutable struct AdminAccountsCreate200Response <: OpenAPI.APIModel
    token::Union{Nothing, String} = nothing

    function AdminAccountsCreate200Response(token, )
        OpenAPI.validate_property(AdminAccountsCreate200Response, Symbol("token"), token)
        return new(token, )
    end
end # type AdminAccountsCreate200Response

const _property_types_AdminAccountsCreate200Response = Dict{Symbol,String}(Symbol("token")=>"String", )
OpenAPI.property_type(::Type{ AdminAccountsCreate200Response }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_AdminAccountsCreate200Response[name]))}

function check_required(o::AdminAccountsCreate200Response)
    o.token === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ AdminAccountsCreate200Response }, name::Symbol, val)
end
