# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""admin___get_table_stats_200_response_value

    AdminGetTableStats200ResponseValue(;
        count=nothing,
        size=nothing,
    )

    - count::Float64
    - size::Float64
"""
Base.@kwdef mutable struct AdminGetTableStats200ResponseValue <: OpenAPI.APIModel
    count::Union{Nothing, Float64} = nothing
    size::Union{Nothing, Float64} = nothing

    function AdminGetTableStats200ResponseValue(count, size, )
        OpenAPI.validate_property(AdminGetTableStats200ResponseValue, Symbol("count"), count)
        OpenAPI.validate_property(AdminGetTableStats200ResponseValue, Symbol("size"), size)
        return new(count, size, )
    end
end # type AdminGetTableStats200ResponseValue

const _property_types_AdminGetTableStats200ResponseValue = Dict{Symbol,String}(Symbol("count")=>"Float64", Symbol("size")=>"Float64", )
OpenAPI.property_type(::Type{ AdminGetTableStats200ResponseValue }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_AdminGetTableStats200ResponseValue[name]))}

function check_required(o::AdminGetTableStats200ResponseValue)
    o.count === nothing && (return false)
    o.size === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ AdminGetTableStats200ResponseValue }, name::Symbol, val)
end
