# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""UserDetailedNotMeOnly

    UserDetailedNotMeOnly(;
        url=nothing,
        uri=nothing,
        movedTo=nothing,
        alsoKnownAs=nothing,
        createdAt=nothing,
        updatedAt=nothing,
        lastFetchedAt=nothing,
        bannerUrl=nothing,
        bannerBlurhash=nothing,
        isLocked=nothing,
        isSilenced=nothing,
        isSuspended=nothing,
        description=nothing,
        location=nothing,
        birthday=nothing,
        lang=nothing,
        fields=nothing,
        verifiedLinks=nothing,
        followersCount=nothing,
        followingCount=nothing,
        notesCount=nothing,
        pinnedNoteIds=nothing,
        pinnedNotes=nothing,
        pinnedPageId=nothing,
        pinnedPage=nothing,
        publicReactions=nothing,
        followingVisibility=nothing,
        followersVisibility=nothing,
        twoFactorEnabled=false,
        usePasswordLessLogin=false,
        securityKeys=false,
        roles=nothing,
        memo=nothing,
        moderationNote=nothing,
        isFollowing=nothing,
        isFollowed=nothing,
        hasPendingFollowRequestFromYou=nothing,
        hasPendingFollowRequestToYou=nothing,
        isBlocking=nothing,
        isBlocked=nothing,
        isMuted=nothing,
        isRenoteMuted=nothing,
        notify=nothing,
        withReplies=nothing,
    )

    - url::String
    - uri::String
    - movedTo::String
    - alsoKnownAs::Vector{String}
    - createdAt::ZonedDateTime
    - updatedAt::ZonedDateTime
    - lastFetchedAt::ZonedDateTime
    - bannerUrl::String
    - bannerBlurhash::String
    - isLocked::Bool
    - isSilenced::Bool
    - isSuspended::Bool
    - description::String
    - location::String
    - birthday::String
    - lang::String
    - fields::Vector{IUpdateRequestFieldsInner}
    - verifiedLinks::Vector{String}
    - followersCount::Float64
    - followingCount::Float64
    - notesCount::Float64
    - pinnedNoteIds::Vector{String}
    - pinnedNotes::Vector{Note}
    - pinnedPageId::String
    - pinnedPage::Page
    - publicReactions::Bool
    - followingVisibility::String
    - followersVisibility::String
    - twoFactorEnabled::Bool
    - usePasswordLessLogin::Bool
    - securityKeys::Bool
    - roles::Vector{RoleLite}
    - memo::String
    - moderationNote::String
    - isFollowing::Bool
    - isFollowed::Bool
    - hasPendingFollowRequestFromYou::Bool
    - hasPendingFollowRequestToYou::Bool
    - isBlocking::Bool
    - isBlocked::Bool
    - isMuted::Bool
    - isRenoteMuted::Bool
    - notify::String
    - withReplies::Bool
"""
Base.@kwdef mutable struct UserDetailedNotMeOnly <: OpenAPI.APIModel
    url::Union{Nothing, String} = nothing
    uri::Union{Nothing, String} = nothing
    movedTo::Union{Nothing, String} = nothing
    alsoKnownAs::Union{Nothing, Vector{String}} = nothing
    createdAt::Union{Nothing, ZonedDateTime} = nothing
    updatedAt::Union{Nothing, ZonedDateTime} = nothing
    lastFetchedAt::Union{Nothing, ZonedDateTime} = nothing
    bannerUrl::Union{Nothing, String} = nothing
    bannerBlurhash::Union{Nothing, String} = nothing
    isLocked::Union{Nothing, Bool} = nothing
    isSilenced::Union{Nothing, Bool} = nothing
    isSuspended::Union{Nothing, Bool} = nothing
    description::Union{Nothing, String} = nothing
    location::Union{Nothing, String} = nothing
    birthday::Union{Nothing, String} = nothing
    lang::Union{Nothing, String} = nothing
    fields::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{IUpdateRequestFieldsInner} }
    verifiedLinks::Union{Nothing, Vector{String}} = nothing
    followersCount::Union{Nothing, Float64} = nothing
    followingCount::Union{Nothing, Float64} = nothing
    notesCount::Union{Nothing, Float64} = nothing
    pinnedNoteIds::Union{Nothing, Vector{String}} = nothing
    pinnedNotes::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{Note} }
    pinnedPageId::Union{Nothing, String} = nothing
    pinnedPage = nothing # spec type: Union{ Nothing, Page }
    publicReactions::Union{Nothing, Bool} = nothing
    followingVisibility::Union{Nothing, String} = nothing
    followersVisibility::Union{Nothing, String} = nothing
    twoFactorEnabled::Union{Nothing, Bool} = false
    usePasswordLessLogin::Union{Nothing, Bool} = false
    securityKeys::Union{Nothing, Bool} = false
    roles::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{RoleLite} }
    memo::Union{Nothing, String} = nothing
    moderationNote::Union{Nothing, String} = nothing
    isFollowing::Union{Nothing, Bool} = nothing
    isFollowed::Union{Nothing, Bool} = nothing
    hasPendingFollowRequestFromYou::Union{Nothing, Bool} = nothing
    hasPendingFollowRequestToYou::Union{Nothing, Bool} = nothing
    isBlocking::Union{Nothing, Bool} = nothing
    isBlocked::Union{Nothing, Bool} = nothing
    isMuted::Union{Nothing, Bool} = nothing
    isRenoteMuted::Union{Nothing, Bool} = nothing
    notify::Union{Nothing, String} = nothing
    withReplies::Union{Nothing, Bool} = nothing

    function UserDetailedNotMeOnly(url, uri, movedTo, alsoKnownAs, createdAt, updatedAt, lastFetchedAt, bannerUrl, bannerBlurhash, isLocked, isSilenced, isSuspended, description, location, birthday, lang, fields, verifiedLinks, followersCount, followingCount, notesCount, pinnedNoteIds, pinnedNotes, pinnedPageId, pinnedPage, publicReactions, followingVisibility, followersVisibility, twoFactorEnabled, usePasswordLessLogin, securityKeys, roles, memo, moderationNote, isFollowing, isFollowed, hasPendingFollowRequestFromYou, hasPendingFollowRequestToYou, isBlocking, isBlocked, isMuted, isRenoteMuted, notify, withReplies, )
        OpenAPI.validate_property(UserDetailedNotMeOnly, Symbol("url"), url)
        OpenAPI.validate_property(UserDetailedNotMeOnly, Symbol("uri"), uri)
        OpenAPI.validate_property(UserDetailedNotMeOnly, Symbol("movedTo"), movedTo)
        OpenAPI.validate_property(UserDetailedNotMeOnly, Symbol("alsoKnownAs"), alsoKnownAs)
        OpenAPI.validate_property(UserDetailedNotMeOnly, Symbol("createdAt"), createdAt)
        OpenAPI.validate_property(UserDetailedNotMeOnly, Symbol("updatedAt"), updatedAt)
        OpenAPI.validate_property(UserDetailedNotMeOnly, Symbol("lastFetchedAt"), lastFetchedAt)
        OpenAPI.validate_property(UserDetailedNotMeOnly, Symbol("bannerUrl"), bannerUrl)
        OpenAPI.validate_property(UserDetailedNotMeOnly, Symbol("bannerBlurhash"), bannerBlurhash)
        OpenAPI.validate_property(UserDetailedNotMeOnly, Symbol("isLocked"), isLocked)
        OpenAPI.validate_property(UserDetailedNotMeOnly, Symbol("isSilenced"), isSilenced)
        OpenAPI.validate_property(UserDetailedNotMeOnly, Symbol("isSuspended"), isSuspended)
        OpenAPI.validate_property(UserDetailedNotMeOnly, Symbol("description"), description)
        OpenAPI.validate_property(UserDetailedNotMeOnly, Symbol("location"), location)
        OpenAPI.validate_property(UserDetailedNotMeOnly, Symbol("birthday"), birthday)
        OpenAPI.validate_property(UserDetailedNotMeOnly, Symbol("lang"), lang)
        OpenAPI.validate_property(UserDetailedNotMeOnly, Symbol("fields"), fields)
        OpenAPI.validate_property(UserDetailedNotMeOnly, Symbol("verifiedLinks"), verifiedLinks)
        OpenAPI.validate_property(UserDetailedNotMeOnly, Symbol("followersCount"), followersCount)
        OpenAPI.validate_property(UserDetailedNotMeOnly, Symbol("followingCount"), followingCount)
        OpenAPI.validate_property(UserDetailedNotMeOnly, Symbol("notesCount"), notesCount)
        OpenAPI.validate_property(UserDetailedNotMeOnly, Symbol("pinnedNoteIds"), pinnedNoteIds)
        OpenAPI.validate_property(UserDetailedNotMeOnly, Symbol("pinnedNotes"), pinnedNotes)
        OpenAPI.validate_property(UserDetailedNotMeOnly, Symbol("pinnedPageId"), pinnedPageId)
        OpenAPI.validate_property(UserDetailedNotMeOnly, Symbol("pinnedPage"), pinnedPage)
        OpenAPI.validate_property(UserDetailedNotMeOnly, Symbol("publicReactions"), publicReactions)
        OpenAPI.validate_property(UserDetailedNotMeOnly, Symbol("followingVisibility"), followingVisibility)
        OpenAPI.validate_property(UserDetailedNotMeOnly, Symbol("followersVisibility"), followersVisibility)
        OpenAPI.validate_property(UserDetailedNotMeOnly, Symbol("twoFactorEnabled"), twoFactorEnabled)
        OpenAPI.validate_property(UserDetailedNotMeOnly, Symbol("usePasswordLessLogin"), usePasswordLessLogin)
        OpenAPI.validate_property(UserDetailedNotMeOnly, Symbol("securityKeys"), securityKeys)
        OpenAPI.validate_property(UserDetailedNotMeOnly, Symbol("roles"), roles)
        OpenAPI.validate_property(UserDetailedNotMeOnly, Symbol("memo"), memo)
        OpenAPI.validate_property(UserDetailedNotMeOnly, Symbol("moderationNote"), moderationNote)
        OpenAPI.validate_property(UserDetailedNotMeOnly, Symbol("isFollowing"), isFollowing)
        OpenAPI.validate_property(UserDetailedNotMeOnly, Symbol("isFollowed"), isFollowed)
        OpenAPI.validate_property(UserDetailedNotMeOnly, Symbol("hasPendingFollowRequestFromYou"), hasPendingFollowRequestFromYou)
        OpenAPI.validate_property(UserDetailedNotMeOnly, Symbol("hasPendingFollowRequestToYou"), hasPendingFollowRequestToYou)
        OpenAPI.validate_property(UserDetailedNotMeOnly, Symbol("isBlocking"), isBlocking)
        OpenAPI.validate_property(UserDetailedNotMeOnly, Symbol("isBlocked"), isBlocked)
        OpenAPI.validate_property(UserDetailedNotMeOnly, Symbol("isMuted"), isMuted)
        OpenAPI.validate_property(UserDetailedNotMeOnly, Symbol("isRenoteMuted"), isRenoteMuted)
        OpenAPI.validate_property(UserDetailedNotMeOnly, Symbol("notify"), notify)
        OpenAPI.validate_property(UserDetailedNotMeOnly, Symbol("withReplies"), withReplies)
        return new(url, uri, movedTo, alsoKnownAs, createdAt, updatedAt, lastFetchedAt, bannerUrl, bannerBlurhash, isLocked, isSilenced, isSuspended, description, location, birthday, lang, fields, verifiedLinks, followersCount, followingCount, notesCount, pinnedNoteIds, pinnedNotes, pinnedPageId, pinnedPage, publicReactions, followingVisibility, followersVisibility, twoFactorEnabled, usePasswordLessLogin, securityKeys, roles, memo, moderationNote, isFollowing, isFollowed, hasPendingFollowRequestFromYou, hasPendingFollowRequestToYou, isBlocking, isBlocked, isMuted, isRenoteMuted, notify, withReplies, )
    end
end # type UserDetailedNotMeOnly

const _property_types_UserDetailedNotMeOnly = Dict{Symbol,String}(Symbol("url")=>"String", Symbol("uri")=>"String", Symbol("movedTo")=>"String", Symbol("alsoKnownAs")=>"Vector{String}", Symbol("createdAt")=>"ZonedDateTime", Symbol("updatedAt")=>"ZonedDateTime", Symbol("lastFetchedAt")=>"ZonedDateTime", Symbol("bannerUrl")=>"String", Symbol("bannerBlurhash")=>"String", Symbol("isLocked")=>"Bool", Symbol("isSilenced")=>"Bool", Symbol("isSuspended")=>"Bool", Symbol("description")=>"String", Symbol("location")=>"String", Symbol("birthday")=>"String", Symbol("lang")=>"String", Symbol("fields")=>"Vector{IUpdateRequestFieldsInner}", Symbol("verifiedLinks")=>"Vector{String}", Symbol("followersCount")=>"Float64", Symbol("followingCount")=>"Float64", Symbol("notesCount")=>"Float64", Symbol("pinnedNoteIds")=>"Vector{String}", Symbol("pinnedNotes")=>"Vector{Note}", Symbol("pinnedPageId")=>"String", Symbol("pinnedPage")=>"Page", Symbol("publicReactions")=>"Bool", Symbol("followingVisibility")=>"String", Symbol("followersVisibility")=>"String", Symbol("twoFactorEnabled")=>"Bool", Symbol("usePasswordLessLogin")=>"Bool", Symbol("securityKeys")=>"Bool", Symbol("roles")=>"Vector{RoleLite}", Symbol("memo")=>"String", Symbol("moderationNote")=>"String", Symbol("isFollowing")=>"Bool", Symbol("isFollowed")=>"Bool", Symbol("hasPendingFollowRequestFromYou")=>"Bool", Symbol("hasPendingFollowRequestToYou")=>"Bool", Symbol("isBlocking")=>"Bool", Symbol("isBlocked")=>"Bool", Symbol("isMuted")=>"Bool", Symbol("isRenoteMuted")=>"Bool", Symbol("notify")=>"String", Symbol("withReplies")=>"Bool", )
OpenAPI.property_type(::Type{ UserDetailedNotMeOnly }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_UserDetailedNotMeOnly[name]))}

function check_required(o::UserDetailedNotMeOnly)
    o.url === nothing && (return false)
    o.uri === nothing && (return false)
    o.movedTo === nothing && (return false)
    o.alsoKnownAs === nothing && (return false)
    o.createdAt === nothing && (return false)
    o.updatedAt === nothing && (return false)
    o.lastFetchedAt === nothing && (return false)
    o.bannerUrl === nothing && (return false)
    o.bannerBlurhash === nothing && (return false)
    o.isLocked === nothing && (return false)
    o.isSilenced === nothing && (return false)
    o.isSuspended === nothing && (return false)
    o.description === nothing && (return false)
    o.location === nothing && (return false)
    o.birthday === nothing && (return false)
    o.lang === nothing && (return false)
    o.fields === nothing && (return false)
    o.verifiedLinks === nothing && (return false)
    o.followersCount === nothing && (return false)
    o.followingCount === nothing && (return false)
    o.notesCount === nothing && (return false)
    o.pinnedNoteIds === nothing && (return false)
    o.pinnedNotes === nothing && (return false)
    o.pinnedPageId === nothing && (return false)
    o.pinnedPage === nothing && (return false)
    o.publicReactions === nothing && (return false)
    o.followingVisibility === nothing && (return false)
    o.followersVisibility === nothing && (return false)
    o.twoFactorEnabled === nothing && (return false)
    o.usePasswordLessLogin === nothing && (return false)
    o.securityKeys === nothing && (return false)
    o.roles === nothing && (return false)
    o.memo === nothing && (return false)
    o.moderationNote === nothing && (return false)
    o.isFollowing === nothing && (return false)
    o.isFollowed === nothing && (return false)
    o.hasPendingFollowRequestFromYou === nothing && (return false)
    o.hasPendingFollowRequestToYou === nothing && (return false)
    o.isBlocking === nothing && (return false)
    o.isBlocked === nothing && (return false)
    o.isMuted === nothing && (return false)
    o.isRenoteMuted === nothing && (return false)
    o.notify === nothing && (return false)
    o.withReplies === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ UserDetailedNotMeOnly }, name::Symbol, val)
    if name === Symbol("url")
        OpenAPI.validate_param(name, "UserDetailedNotMeOnly", :format, val, "url")
    end
    if name === Symbol("uri")
        OpenAPI.validate_param(name, "UserDetailedNotMeOnly", :format, val, "uri")
    end
    if name === Symbol("movedTo")
        OpenAPI.validate_param(name, "UserDetailedNotMeOnly", :format, val, "uri")
    end
    if name === Symbol("createdAt")
        OpenAPI.validate_param(name, "UserDetailedNotMeOnly", :format, val, "date-time")
    end
    if name === Symbol("updatedAt")
        OpenAPI.validate_param(name, "UserDetailedNotMeOnly", :format, val, "date-time")
    end
    if name === Symbol("lastFetchedAt")
        OpenAPI.validate_param(name, "UserDetailedNotMeOnly", :format, val, "date-time")
    end
    if name === Symbol("bannerUrl")
        OpenAPI.validate_param(name, "UserDetailedNotMeOnly", :format, val, "url")
    end
    if name === Symbol("fields")
        OpenAPI.validate_param(name, "UserDetailedNotMeOnly", :maxItems, val, 16)
    end
    if name === Symbol("followingVisibility")
        OpenAPI.validate_param(name, "UserDetailedNotMeOnly", :enum, val, ["public", "followers", "private"])
    end
    if name === Symbol("followersVisibility")
        OpenAPI.validate_param(name, "UserDetailedNotMeOnly", :enum, val, ["public", "followers", "private"])
    end
    if name === Symbol("notify")
        OpenAPI.validate_param(name, "UserDetailedNotMeOnly", :enum, val, ["normal", "none"])
    end
end
