# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""Notification_oneOf_4

    NotificationOneOf4(;
        id=nothing,
        createdAt=nothing,
        type=nothing,
        user=nothing,
        userId=nothing,
        note=nothing,
    )

    - id::String
    - createdAt::ZonedDateTime
    - type::String
    - user::UserLite
    - userId::String
    - note::Note
"""
Base.@kwdef mutable struct NotificationOneOf4 <: OpenAPI.APIModel
    id::Union{Nothing, String} = nothing
    createdAt::Union{Nothing, ZonedDateTime} = nothing
    type::Union{Nothing, String} = nothing
    user = nothing # spec type: Union{ Nothing, UserLite }
    userId::Union{Nothing, String} = nothing
    note = nothing # spec type: Union{ Nothing, Note }

    function NotificationOneOf4(id, createdAt, type, user, userId, note, )
        OpenAPI.validate_property(NotificationOneOf4, Symbol("id"), id)
        OpenAPI.validate_property(NotificationOneOf4, Symbol("createdAt"), createdAt)
        OpenAPI.validate_property(NotificationOneOf4, Symbol("type"), type)
        OpenAPI.validate_property(NotificationOneOf4, Symbol("user"), user)
        OpenAPI.validate_property(NotificationOneOf4, Symbol("userId"), userId)
        OpenAPI.validate_property(NotificationOneOf4, Symbol("note"), note)
        return new(id, createdAt, type, user, userId, note, )
    end
end # type NotificationOneOf4

const _property_types_NotificationOneOf4 = Dict{Symbol,String}(Symbol("id")=>"String", Symbol("createdAt")=>"ZonedDateTime", Symbol("type")=>"String", Symbol("user")=>"UserLite", Symbol("userId")=>"String", Symbol("note")=>"Note", )
OpenAPI.property_type(::Type{ NotificationOneOf4 }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_NotificationOneOf4[name]))}

function check_required(o::NotificationOneOf4)
    o.id === nothing && (return false)
    o.createdAt === nothing && (return false)
    o.type === nothing && (return false)
    o.user === nothing && (return false)
    o.userId === nothing && (return false)
    o.note === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ NotificationOneOf4 }, name::Symbol, val)
    if name === Symbol("id")
        OpenAPI.validate_param(name, "NotificationOneOf4", :format, val, "id")
    end
    if name === Symbol("createdAt")
        OpenAPI.validate_param(name, "NotificationOneOf4", :format, val, "date-time")
    end
    if name === Symbol("type")
        OpenAPI.validate_param(name, "NotificationOneOf4", :enum, val, ["quote"])
    end
    if name === Symbol("userId")
        OpenAPI.validate_param(name, "NotificationOneOf4", :format, val, "id")
    end
end
