# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""clips___delete_request

    ClipsDeleteRequest(;
        clipId=nothing,
    )

    - clipId::String
"""
Base.@kwdef mutable struct ClipsDeleteRequest <: OpenAPI.APIModel
    clipId::Union{Nothing, String} = nothing

    function ClipsDeleteRequest(clipId, )
        OpenAPI.validate_property(ClipsDeleteRequest, Symbol("clipId"), clipId)
        return new(clipId, )
    end
end # type ClipsDeleteRequest

const _property_types_ClipsDeleteRequest = Dict{Symbol,String}(Symbol("clipId")=>"String", )
OpenAPI.property_type(::Type{ ClipsDeleteRequest }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ClipsDeleteRequest[name]))}

function check_required(o::ClipsDeleteRequest)
    o.clipId === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ ClipsDeleteRequest }, name::Symbol, val)
    if name === Symbol("clipId")
        OpenAPI.validate_param(name, "ClipsDeleteRequest", :format, val, "misskey:id")
    end
end
