# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""following___update_all_request

    FollowingUpdateAllRequest(;
        notify=nothing,
        withReplies=nothing,
    )

    - notify::String
    - withReplies::Bool
"""
Base.@kwdef mutable struct FollowingUpdateAllRequest <: OpenAPI.APIModel
    notify::Union{Nothing, String} = nothing
    withReplies::Union{Nothing, Bool} = nothing

    function FollowingUpdateAllRequest(notify, withReplies, )
        OpenAPI.validate_property(FollowingUpdateAllRequest, Symbol("notify"), notify)
        OpenAPI.validate_property(FollowingUpdateAllRequest, Symbol("withReplies"), withReplies)
        return new(notify, withReplies, )
    end
end # type FollowingUpdateAllRequest

const _property_types_FollowingUpdateAllRequest = Dict{Symbol,String}(Symbol("notify")=>"String", Symbol("withReplies")=>"Bool", )
OpenAPI.property_type(::Type{ FollowingUpdateAllRequest }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_FollowingUpdateAllRequest[name]))}

function check_required(o::FollowingUpdateAllRequest)
    true
end

function OpenAPI.validate_property(::Type{ FollowingUpdateAllRequest }, name::Symbol, val)
    if name === Symbol("notify")
        OpenAPI.validate_param(name, "FollowingUpdateAllRequest", :enum, val, ["normal", "none"])
    end
end
