# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""endpoint_200_response_params_inner

    Endpoint200ResponseParamsInner(;
        name=nothing,
        type=nothing,
    )

    - name::String
    - type::String
"""
Base.@kwdef mutable struct Endpoint200ResponseParamsInner <: OpenAPI.APIModel
    name::Union{Nothing, String} = nothing
    type::Union{Nothing, String} = nothing

    function Endpoint200ResponseParamsInner(name, type, )
        OpenAPI.validate_property(Endpoint200ResponseParamsInner, Symbol("name"), name)
        OpenAPI.validate_property(Endpoint200ResponseParamsInner, Symbol("type"), type)
        return new(name, type, )
    end
end # type Endpoint200ResponseParamsInner

const _property_types_Endpoint200ResponseParamsInner = Dict{Symbol,String}(Symbol("name")=>"String", Symbol("type")=>"String", )
OpenAPI.property_type(::Type{ Endpoint200ResponseParamsInner }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_Endpoint200ResponseParamsInner[name]))}

function check_required(o::Endpoint200ResponseParamsInner)
    o.name === nothing && (return false)
    o.type === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ Endpoint200ResponseParamsInner }, name::Symbol, val)
end
