# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""drive___folders___create_request

    DriveFoldersCreateRequest(;
        name="Untitled",
        parentId=nothing,
    )

    - name::String
    - parentId::String
"""
Base.@kwdef mutable struct DriveFoldersCreateRequest <: OpenAPI.APIModel
    name::Union{Nothing, String} = "Untitled"
    parentId::Union{Nothing, String} = nothing

    function DriveFoldersCreateRequest(name, parentId, )
        OpenAPI.validate_property(DriveFoldersCreateRequest, Symbol("name"), name)
        OpenAPI.validate_property(DriveFoldersCreateRequest, Symbol("parentId"), parentId)
        return new(name, parentId, )
    end
end # type DriveFoldersCreateRequest

const _property_types_DriveFoldersCreateRequest = Dict{Symbol,String}(Symbol("name")=>"String", Symbol("parentId")=>"String", )
OpenAPI.property_type(::Type{ DriveFoldersCreateRequest }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_DriveFoldersCreateRequest[name]))}

function check_required(o::DriveFoldersCreateRequest)
    true
end

function OpenAPI.validate_property(::Type{ DriveFoldersCreateRequest }, name::Symbol, val)
    if name === Symbol("name")
        OpenAPI.validate_param(name, "DriveFoldersCreateRequest", :maxLength, val, 200)
    end
    if name === Symbol("parentId")
        OpenAPI.validate_param(name, "DriveFoldersCreateRequest", :format, val, "misskey:id")
    end
end
