# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""admin___ad___update_request

    AdminAdUpdateRequest(;
        id=nothing,
        memo=nothing,
        url=nothing,
        imageUrl=nothing,
        place=nothing,
        priority=nothing,
        ratio=nothing,
        expiresAt=nothing,
        startsAt=nothing,
        dayOfWeek=nothing,
    )

    - id::String
    - memo::String
    - url::String
    - imageUrl::String
    - place::String
    - priority::String
    - ratio::Int64
    - expiresAt::Int64
    - startsAt::Int64
    - dayOfWeek::Int64
"""
Base.@kwdef mutable struct AdminAdUpdateRequest <: OpenAPI.APIModel
    id::Union{Nothing, String} = nothing
    memo::Union{Nothing, String} = nothing
    url::Union{Nothing, String} = nothing
    imageUrl::Union{Nothing, String} = nothing
    place::Union{Nothing, String} = nothing
    priority::Union{Nothing, String} = nothing
    ratio::Union{Nothing, Int64} = nothing
    expiresAt::Union{Nothing, Int64} = nothing
    startsAt::Union{Nothing, Int64} = nothing
    dayOfWeek::Union{Nothing, Int64} = nothing

    function AdminAdUpdateRequest(id, memo, url, imageUrl, place, priority, ratio, expiresAt, startsAt, dayOfWeek, )
        OpenAPI.validate_property(AdminAdUpdateRequest, Symbol("id"), id)
        OpenAPI.validate_property(AdminAdUpdateRequest, Symbol("memo"), memo)
        OpenAPI.validate_property(AdminAdUpdateRequest, Symbol("url"), url)
        OpenAPI.validate_property(AdminAdUpdateRequest, Symbol("imageUrl"), imageUrl)
        OpenAPI.validate_property(AdminAdUpdateRequest, Symbol("place"), place)
        OpenAPI.validate_property(AdminAdUpdateRequest, Symbol("priority"), priority)
        OpenAPI.validate_property(AdminAdUpdateRequest, Symbol("ratio"), ratio)
        OpenAPI.validate_property(AdminAdUpdateRequest, Symbol("expiresAt"), expiresAt)
        OpenAPI.validate_property(AdminAdUpdateRequest, Symbol("startsAt"), startsAt)
        OpenAPI.validate_property(AdminAdUpdateRequest, Symbol("dayOfWeek"), dayOfWeek)
        return new(id, memo, url, imageUrl, place, priority, ratio, expiresAt, startsAt, dayOfWeek, )
    end
end # type AdminAdUpdateRequest

const _property_types_AdminAdUpdateRequest = Dict{Symbol,String}(Symbol("id")=>"String", Symbol("memo")=>"String", Symbol("url")=>"String", Symbol("imageUrl")=>"String", Symbol("place")=>"String", Symbol("priority")=>"String", Symbol("ratio")=>"Int64", Symbol("expiresAt")=>"Int64", Symbol("startsAt")=>"Int64", Symbol("dayOfWeek")=>"Int64", )
OpenAPI.property_type(::Type{ AdminAdUpdateRequest }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_AdminAdUpdateRequest[name]))}

function check_required(o::AdminAdUpdateRequest)
    o.id === nothing && (return false)
    o.memo === nothing && (return false)
    o.url === nothing && (return false)
    o.imageUrl === nothing && (return false)
    o.place === nothing && (return false)
    o.priority === nothing && (return false)
    o.ratio === nothing && (return false)
    o.expiresAt === nothing && (return false)
    o.startsAt === nothing && (return false)
    o.dayOfWeek === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ AdminAdUpdateRequest }, name::Symbol, val)
    if name === Symbol("id")
        OpenAPI.validate_param(name, "AdminAdUpdateRequest", :format, val, "misskey:id")
    end
    if name === Symbol("url")
        OpenAPI.validate_param(name, "AdminAdUpdateRequest", :minLength, val, 1)
    end
    if name === Symbol("imageUrl")
        OpenAPI.validate_param(name, "AdminAdUpdateRequest", :minLength, val, 1)
    end
end
