# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""admin___show_users_request

    AdminShowUsersRequest(;
        limit=10,
        offset=0,
        sort=nothing,
        state="all",
        origin="combined",
        username=nothing,
        hostname=nothing,
    )

    - limit::Int64
    - offset::Int64
    - sort::String
    - state::String
    - origin::String
    - username::String
    - hostname::String : The local host is represented with &#x60;null&#x60;.
"""
Base.@kwdef mutable struct AdminShowUsersRequest <: OpenAPI.APIModel
    limit::Union{Nothing, Int64} = 10
    offset::Union{Nothing, Int64} = 0
    sort::Union{Nothing, String} = nothing
    state::Union{Nothing, String} = "all"
    origin::Union{Nothing, String} = "combined"
    username::Union{Nothing, String} = nothing
    hostname::Union{Nothing, String} = nothing

    function AdminShowUsersRequest(limit, offset, sort, state, origin, username, hostname, )
        OpenAPI.validate_property(AdminShowUsersRequest, Symbol("limit"), limit)
        OpenAPI.validate_property(AdminShowUsersRequest, Symbol("offset"), offset)
        OpenAPI.validate_property(AdminShowUsersRequest, Symbol("sort"), sort)
        OpenAPI.validate_property(AdminShowUsersRequest, Symbol("state"), state)
        OpenAPI.validate_property(AdminShowUsersRequest, Symbol("origin"), origin)
        OpenAPI.validate_property(AdminShowUsersRequest, Symbol("username"), username)
        OpenAPI.validate_property(AdminShowUsersRequest, Symbol("hostname"), hostname)
        return new(limit, offset, sort, state, origin, username, hostname, )
    end
end # type AdminShowUsersRequest

const _property_types_AdminShowUsersRequest = Dict{Symbol,String}(Symbol("limit")=>"Int64", Symbol("offset")=>"Int64", Symbol("sort")=>"String", Symbol("state")=>"String", Symbol("origin")=>"String", Symbol("username")=>"String", Symbol("hostname")=>"String", )
OpenAPI.property_type(::Type{ AdminShowUsersRequest }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_AdminShowUsersRequest[name]))}

function check_required(o::AdminShowUsersRequest)
    true
end

function OpenAPI.validate_property(::Type{ AdminShowUsersRequest }, name::Symbol, val)
    if name === Symbol("limit")
        OpenAPI.validate_param(name, "AdminShowUsersRequest", :maximum, val, 100, false)
        OpenAPI.validate_param(name, "AdminShowUsersRequest", :minimum, val, 1, false)
    end
    if name === Symbol("sort")
        OpenAPI.validate_param(name, "AdminShowUsersRequest", :enum, val, ["+follower", "-follower", "+createdAt", "-createdAt", "+updatedAt", "-updatedAt", "+lastActiveDate", "-lastActiveDate"])
    end
    if name === Symbol("state")
        OpenAPI.validate_param(name, "AdminShowUsersRequest", :enum, val, ["all", "alive", "available", "admin", "moderator", "adminOrModerator", "suspended"])
    end
    if name === Symbol("origin")
        OpenAPI.validate_param(name, "AdminShowUsersRequest", :enum, val, ["combined", "local", "remote"])
    end
end
