# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""users___clips_request

    UsersClipsRequest(;
        userId=nothing,
        limit=10,
        sinceId=nothing,
        untilId=nothing,
    )

    - userId::String
    - limit::Int64
    - sinceId::String
    - untilId::String
"""
Base.@kwdef mutable struct UsersClipsRequest <: OpenAPI.APIModel
    userId::Union{Nothing, String} = nothing
    limit::Union{Nothing, Int64} = 10
    sinceId::Union{Nothing, String} = nothing
    untilId::Union{Nothing, String} = nothing

    function UsersClipsRequest(userId, limit, sinceId, untilId, )
        OpenAPI.validate_property(UsersClipsRequest, Symbol("userId"), userId)
        OpenAPI.validate_property(UsersClipsRequest, Symbol("limit"), limit)
        OpenAPI.validate_property(UsersClipsRequest, Symbol("sinceId"), sinceId)
        OpenAPI.validate_property(UsersClipsRequest, Symbol("untilId"), untilId)
        return new(userId, limit, sinceId, untilId, )
    end
end # type UsersClipsRequest

const _property_types_UsersClipsRequest = Dict{Symbol,String}(Symbol("userId")=>"String", Symbol("limit")=>"Int64", Symbol("sinceId")=>"String", Symbol("untilId")=>"String", )
OpenAPI.property_type(::Type{ UsersClipsRequest }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_UsersClipsRequest[name]))}

function check_required(o::UsersClipsRequest)
    o.userId === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ UsersClipsRequest }, name::Symbol, val)
    if name === Symbol("userId")
        OpenAPI.validate_param(name, "UsersClipsRequest", :format, val, "misskey:id")
    end
    if name === Symbol("limit")
        OpenAPI.validate_param(name, "UsersClipsRequest", :maximum, val, 100, false)
        OpenAPI.validate_param(name, "UsersClipsRequest", :minimum, val, 1, false)
    end
    if name === Symbol("sinceId")
        OpenAPI.validate_param(name, "UsersClipsRequest", :format, val, "misskey:id")
    end
    if name === Symbol("untilId")
        OpenAPI.validate_param(name, "UsersClipsRequest", :format, val, "misskey:id")
    end
end
