# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""admin___ad___list_request

    AdminAdListRequest(;
        limit=10,
        sinceId=nothing,
        untilId=nothing,
        publishing=null,
    )

    - limit::Int64
    - sinceId::String
    - untilId::String
    - publishing::Bool
"""
Base.@kwdef mutable struct AdminAdListRequest <: OpenAPI.APIModel
    limit::Union{Nothing, Int64} = 10
    sinceId::Union{Nothing, String} = nothing
    untilId::Union{Nothing, String} = nothing
    publishing::Union{Nothing, Bool} = null

    function AdminAdListRequest(limit, sinceId, untilId, publishing, )
        OpenAPI.validate_property(AdminAdListRequest, Symbol("limit"), limit)
        OpenAPI.validate_property(AdminAdListRequest, Symbol("sinceId"), sinceId)
        OpenAPI.validate_property(AdminAdListRequest, Symbol("untilId"), untilId)
        OpenAPI.validate_property(AdminAdListRequest, Symbol("publishing"), publishing)
        return new(limit, sinceId, untilId, publishing, )
    end
end # type AdminAdListRequest

const _property_types_AdminAdListRequest = Dict{Symbol,String}(Symbol("limit")=>"Int64", Symbol("sinceId")=>"String", Symbol("untilId")=>"String", Symbol("publishing")=>"Bool", )
OpenAPI.property_type(::Type{ AdminAdListRequest }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_AdminAdListRequest[name]))}

function check_required(o::AdminAdListRequest)
    true
end

function OpenAPI.validate_property(::Type{ AdminAdListRequest }, name::Symbol, val)
    if name === Symbol("limit")
        OpenAPI.validate_param(name, "AdminAdListRequest", :maximum, val, 100, false)
        OpenAPI.validate_param(name, "AdminAdListRequest", :minimum, val, 1, false)
    end
    if name === Symbol("sinceId")
        OpenAPI.validate_param(name, "AdminAdListRequest", :format, val, "misskey:id")
    end
    if name === Symbol("untilId")
        OpenAPI.validate_param(name, "AdminAdListRequest", :format, val, "misskey:id")
    end
end
