# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""drive___files___attached_notes_request

    DriveFilesAttachedNotesRequest(;
        sinceId=nothing,
        untilId=nothing,
        limit=10,
        fileId=nothing,
    )

    - sinceId::String
    - untilId::String
    - limit::Int64
    - fileId::String
"""
Base.@kwdef mutable struct DriveFilesAttachedNotesRequest <: OpenAPI.APIModel
    sinceId::Union{Nothing, String} = nothing
    untilId::Union{Nothing, String} = nothing
    limit::Union{Nothing, Int64} = 10
    fileId::Union{Nothing, String} = nothing

    function DriveFilesAttachedNotesRequest(sinceId, untilId, limit, fileId, )
        OpenAPI.validate_property(DriveFilesAttachedNotesRequest, Symbol("sinceId"), sinceId)
        OpenAPI.validate_property(DriveFilesAttachedNotesRequest, Symbol("untilId"), untilId)
        OpenAPI.validate_property(DriveFilesAttachedNotesRequest, Symbol("limit"), limit)
        OpenAPI.validate_property(DriveFilesAttachedNotesRequest, Symbol("fileId"), fileId)
        return new(sinceId, untilId, limit, fileId, )
    end
end # type DriveFilesAttachedNotesRequest

const _property_types_DriveFilesAttachedNotesRequest = Dict{Symbol,String}(Symbol("sinceId")=>"String", Symbol("untilId")=>"String", Symbol("limit")=>"Int64", Symbol("fileId")=>"String", )
OpenAPI.property_type(::Type{ DriveFilesAttachedNotesRequest }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_DriveFilesAttachedNotesRequest[name]))}

function check_required(o::DriveFilesAttachedNotesRequest)
    o.fileId === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ DriveFilesAttachedNotesRequest }, name::Symbol, val)
    if name === Symbol("sinceId")
        OpenAPI.validate_param(name, "DriveFilesAttachedNotesRequest", :format, val, "misskey:id")
    end
    if name === Symbol("untilId")
        OpenAPI.validate_param(name, "DriveFilesAttachedNotesRequest", :format, val, "misskey:id")
    end
    if name === Symbol("limit")
        OpenAPI.validate_param(name, "DriveFilesAttachedNotesRequest", :maximum, val, 100, false)
        OpenAPI.validate_param(name, "DriveFilesAttachedNotesRequest", :minimum, val, 1, false)
    end
    if name === Symbol("fileId")
        OpenAPI.validate_param(name, "DriveFilesAttachedNotesRequest", :format, val, "misskey:id")
    end
end
