# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""admin___drive___show_file_request

    AdminDriveShowFileRequest(;
        fileId=nothing,
        url=nothing,
    )

    - fileId::String
    - url::String
"""
Base.@kwdef mutable struct AdminDriveShowFileRequest <: OpenAPI.APIModel
    fileId::Union{Nothing, String} = nothing
    url::Union{Nothing, String} = nothing

    function AdminDriveShowFileRequest(fileId, url, )
        OpenAPI.validate_property(AdminDriveShowFileRequest, Symbol("fileId"), fileId)
        OpenAPI.validate_property(AdminDriveShowFileRequest, Symbol("url"), url)
        return new(fileId, url, )
    end
end # type AdminDriveShowFileRequest

const _property_types_AdminDriveShowFileRequest = Dict{Symbol,String}(Symbol("fileId")=>"String", Symbol("url")=>"String", )
OpenAPI.property_type(::Type{ AdminDriveShowFileRequest }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_AdminDriveShowFileRequest[name]))}

function check_required(o::AdminDriveShowFileRequest)
    true
end

function OpenAPI.validate_property(::Type{ AdminDriveShowFileRequest }, name::Symbol, val)
    if name === Symbol("fileId")
        OpenAPI.validate_param(name, "AdminDriveShowFileRequest", :format, val, "misskey:id")
    end
end
