# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""i___2fa___register_key_request

    I2faRegisterKeyRequest(;
        password=nothing,
        token=nothing,
    )

    - password::String
    - token::String
"""
Base.@kwdef mutable struct I2faRegisterKeyRequest <: OpenAPI.APIModel
    password::Union{Nothing, String} = nothing
    token::Union{Nothing, String} = nothing

    function I2faRegisterKeyRequest(password, token, )
        OpenAPI.validate_property(I2faRegisterKeyRequest, Symbol("password"), password)
        OpenAPI.validate_property(I2faRegisterKeyRequest, Symbol("token"), token)
        return new(password, token, )
    end
end # type I2faRegisterKeyRequest

const _property_types_I2faRegisterKeyRequest = Dict{Symbol,String}(Symbol("password")=>"String", Symbol("token")=>"String", )
OpenAPI.property_type(::Type{ I2faRegisterKeyRequest }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_I2faRegisterKeyRequest[name]))}

function check_required(o::I2faRegisterKeyRequest)
    o.password === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ I2faRegisterKeyRequest }, name::Symbol, val)
end
