# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""drive_200_response

    Drive200Response(;
        capacity=nothing,
        usage=nothing,
    )

    - capacity::Float64
    - usage::Float64
"""
Base.@kwdef mutable struct Drive200Response <: OpenAPI.APIModel
    capacity::Union{Nothing, Float64} = nothing
    usage::Union{Nothing, Float64} = nothing

    function Drive200Response(capacity, usage, )
        OpenAPI.validate_property(Drive200Response, Symbol("capacity"), capacity)
        OpenAPI.validate_property(Drive200Response, Symbol("usage"), usage)
        return new(capacity, usage, )
    end
end # type Drive200Response

const _property_types_Drive200Response = Dict{Symbol,String}(Symbol("capacity")=>"Float64", Symbol("usage")=>"Float64", )
OpenAPI.property_type(::Type{ Drive200Response }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_Drive200Response[name]))}

function check_required(o::Drive200Response)
    o.capacity === nothing && (return false)
    o.usage === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ Drive200Response }, name::Symbol, val)
end
