# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""fetch_rss_200_response_1_itunes_owner

    FetchRss200Response1ItunesOwner(;
        name=nothing,
        email=nothing,
    )

    - name::String
    - email::String
"""
Base.@kwdef mutable struct FetchRss200Response1ItunesOwner <: OpenAPI.APIModel
    name::Union{Nothing, String} = nothing
    email::Union{Nothing, String} = nothing

    function FetchRss200Response1ItunesOwner(name, email, )
        OpenAPI.validate_property(FetchRss200Response1ItunesOwner, Symbol("name"), name)
        OpenAPI.validate_property(FetchRss200Response1ItunesOwner, Symbol("email"), email)
        return new(name, email, )
    end
end # type FetchRss200Response1ItunesOwner

const _property_types_FetchRss200Response1ItunesOwner = Dict{Symbol,String}(Symbol("name")=>"String", Symbol("email")=>"String", )
OpenAPI.property_type(::Type{ FetchRss200Response1ItunesOwner }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_FetchRss200Response1ItunesOwner[name]))}

function check_required(o::FetchRss200Response1ItunesOwner)
    true
end

function OpenAPI.validate_property(::Type{ FetchRss200Response1ItunesOwner }, name::Symbol, val)
end
