# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""admin___announcements___list_request

    AdminAnnouncementsListRequest(;
        limit=10,
        sinceId=nothing,
        untilId=nothing,
        userId=nothing,
    )

    - limit::Int64
    - sinceId::String
    - untilId::String
    - userId::String
"""
Base.@kwdef mutable struct AdminAnnouncementsListRequest <: OpenAPI.APIModel
    limit::Union{Nothing, Int64} = 10
    sinceId::Union{Nothing, String} = nothing
    untilId::Union{Nothing, String} = nothing
    userId::Union{Nothing, String} = nothing

    function AdminAnnouncementsListRequest(limit, sinceId, untilId, userId, )
        OpenAPI.validate_property(AdminAnnouncementsListRequest, Symbol("limit"), limit)
        OpenAPI.validate_property(AdminAnnouncementsListRequest, Symbol("sinceId"), sinceId)
        OpenAPI.validate_property(AdminAnnouncementsListRequest, Symbol("untilId"), untilId)
        OpenAPI.validate_property(AdminAnnouncementsListRequest, Symbol("userId"), userId)
        return new(limit, sinceId, untilId, userId, )
    end
end # type AdminAnnouncementsListRequest

const _property_types_AdminAnnouncementsListRequest = Dict{Symbol,String}(Symbol("limit")=>"Int64", Symbol("sinceId")=>"String", Symbol("untilId")=>"String", Symbol("userId")=>"String", )
OpenAPI.property_type(::Type{ AdminAnnouncementsListRequest }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_AdminAnnouncementsListRequest[name]))}

function check_required(o::AdminAnnouncementsListRequest)
    true
end

function OpenAPI.validate_property(::Type{ AdminAnnouncementsListRequest }, name::Symbol, val)
    if name === Symbol("limit")
        OpenAPI.validate_param(name, "AdminAnnouncementsListRequest", :maximum, val, 100, false)
        OpenAPI.validate_param(name, "AdminAnnouncementsListRequest", :minimum, val, 1, false)
    end
    if name === Symbol("sinceId")
        OpenAPI.validate_param(name, "AdminAnnouncementsListRequest", :format, val, "misskey:id")
    end
    if name === Symbol("untilId")
        OpenAPI.validate_param(name, "AdminAnnouncementsListRequest", :format, val, "misskey:id")
    end
    if name === Symbol("userId")
        OpenAPI.validate_param(name, "AdminAnnouncementsListRequest", :format, val, "misskey:id")
    end
end
