# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""charts___users_200_response

    ChartsUsers200Response(;
        var"local"=nothing,
        remote=nothing,
    )

    - var"local"::ChartsInstance200ResponseUsers
    - remote::ChartsInstance200ResponseUsers
"""
Base.@kwdef mutable struct ChartsUsers200Response <: OpenAPI.APIModel
    var"local" = nothing # spec type: Union{ Nothing, ChartsInstance200ResponseUsers }
    remote = nothing # spec type: Union{ Nothing, ChartsInstance200ResponseUsers }

    function ChartsUsers200Response(var"local", remote, )
        OpenAPI.validate_property(ChartsUsers200Response, Symbol("local"), var"local")
        OpenAPI.validate_property(ChartsUsers200Response, Symbol("remote"), remote)
        return new(var"local", remote, )
    end
end # type ChartsUsers200Response

const _property_types_ChartsUsers200Response = Dict{Symbol,String}(Symbol("local")=>"ChartsInstance200ResponseUsers", Symbol("remote")=>"ChartsInstance200ResponseUsers", )
OpenAPI.property_type(::Type{ ChartsUsers200Response }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ChartsUsers200Response[name]))}

function check_required(o::ChartsUsers200Response)
    o.var"local" === nothing && (return false)
    o.remote === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ ChartsUsers200Response }, name::Symbol, val)
end
